[CmdletBinding()]
param([string]$RepoRoot=(Split-Path -Parent $PSScriptRoot))
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repo=(Resolve-Path $RepoRoot).Path
function Read-Json([string]$Path){Get-Content -Raw -LiteralPath $Path|ConvertFrom-Json}
function Write-Json([string]$Path,$Value){New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path)|Out-Null;[IO.File]::WriteAllText($Path,($Value|ConvertTo-Json -Depth 100)+[Environment]::NewLine,[Text.UTF8Encoding]::new($false))}
function Write-Text([string]$Path,[string]$Text){New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path)|Out-Null;[IO.File]::WriteAllText($Path,$Text.TrimStart()+[Environment]::NewLine,[Text.UTF8Encoding]::new($false))}
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Rel([string]$Path){(Resolve-Path -LiteralPath $Path -Relative).ToString().TrimStart('.','\','/').Replace('\','/')}
$out=Join-Path $repo 'artifacts/authority-audit/canonical-batch-v3'
Remove-Item -LiteralPath $out -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force -Path $out,(Join-Path $out 'blockers')|Out-Null
$frozen=@((Read-Json (Join-Path $repo 'artifacts/authority-audit/canonical-batch-v2/document-inventory.json')).documents|Where-Object status -eq 'FROZEN_COMPLETE')
$deep=Read-Json (Join-Path $repo 'artifacts/authority-audit/canonical-deep-adjudication-v3/summary.json')
$new=@($deep.documents)
$rows=[Collections.Generic.List[object]]::new()
foreach($r in $frozen){$rows.Add([ordered]@{docId=$r.docId;status='FROZEN_COMPLETE';sourcePath=$r.sourcePath;sourceSHA256=$r.sourceSHA;occurrenceCount=$r.occurrenceCount;semanticNodeCount=$r.semanticNodeCount;parentEdgeCount=$r.parentEdgeCount;rootChildren=$r.rootChildren;maxDepth=$r.maxDepth;proposalAuthority='EXPLICITLY_FROZEN_EXISTING_AUTHORITY';userApprovalRequired=$false;blockedLayer=$null;reasonCode=$null})}
foreach($r in $new){$bl=$null;$rc=$null;if($r.PSObject.Properties.Name -contains 'blockedLayer'){$bl=$r.blockedLayer};if($r.PSObject.Properties.Name -contains 'reasonCode'){$rc=$r.reasonCode};$rows.Add([ordered]@{docId=$r.docId;status=$r.status;sourcePath=$r.sourcePath;sourceSHA256=$r.sourceSHA256;occurrenceCount=$r.canonicalOccurrenceCount;semanticNodeCount=$r.semanticNodeCount;parentEdgeCount=$r.parentEdgeCount;rootChildren=$r.rootChildren;maxDepth=$r.maxDepth;proposalAuthority=$r.proposalAuthority;userApprovalRequired=[bool]$r.userApprovalRequired;blockedLayer=$bl;reasonCode=$rc})}
$summary=[ordered]@{artifactKind='A99_CANONICAL_BATCH_V3_SUMMARY';schemaVersion='a99-canonical-batch-v3';status='BATCH_V3_READY_FOR_USER_CANONICAL_APPROVAL';baselineCommit='a5ac90b';totalDocuments=$rows.Count;frozenExisting=@($rows|Where-Object status -eq 'FROZEN_COMPLETE').Count;readyForUserApproval=@($rows|Where-Object status -eq 'READY_FOR_USER_APPROVAL_CANONICAL_HIERARCHY').Count;genuineHardBlockers=@($rows|Where-Object status -eq 'GENUINE_HARD_BLOCKER').Count;newOccurrenceAuthorities=$deep.newOccurrenceAuthorities;newIdentityProposals=$deep.newIdentityProposals;newHierarchyProposals=$deep.newHierarchyProposals;newOccurrences=$deep.newOccurrenceTotal;newSemanticNodes=$deep.newSemanticNodeTotal;newParentEdges=$deep.newParentEdgeTotal;aggregateOccurrences=$deep.aggregateOccurrences;aggregateSemanticNodes=$deep.aggregateSemanticNodes;aggregateParentEdges=$deep.aggregateParentEdges;providerCalls=0;productionModelCalls=0;historicalLevelRead=$false;historicalParentRead=$false;historicalHierarchyUsedForDecision=$false;historicalSemanticTotalUsedForDecision=$false;canonicalGoldMutation=$false;newUserReviewedPromotion=$false;documents=@($rows)}
Write-Json (Join-Path $out 'document-inventory.json') ([ordered]@{artifactKind='A99_CANONICAL_BATCH_V3_DOCUMENT_INVENTORY';schemaVersion='a99-canonical-batch-v3';baselineCommit='a5ac90b';documents=@($rows);counts=[ordered]@{total=$rows.Count;frozenExisting=$summary.frozenExisting;readyForUserApproval=$summary.readyForUserApproval;genuineHardBlockers=$summary.genuineHardBlockers};providerCalls=0;productionModelCalls=0;historicalLevelRead=$false;historicalParentRead=$false;canonicalGoldMutation=$false;newUserReviewedPromotion=$false})
Write-Json (Join-Path $out 'batch-summary.json') $summary
$blockers=@($deep.documents|Where-Object status -eq 'GENUINE_HARD_BLOCKER')
foreach($b in $blockers){$src=Join-Path $repo ('artifacts/authority-audit/canonical-deep-adjudication-v3/blockers/{0}.json'-f $b.docId);Write-Json (Join-Path $out "blockers/$($b.docId).json") ([ordered]@{docId=$b.docId;blockedLayer=$b.blockedLayer;reasonCode=$b.reasonCode;sourceAuthority=[ordered]@{path=$b.sourcePath;sha256=$b.sourceSHA256};exactAttemptedMethod='Source-backed structural representation plus exhaustive source scan';evidenceInspected=@('Source document','source-faithful structural records','format/container/heading-like scope evidence');specificUnresolvedFact='Multiple template/form/annex/TOC scopes require a user source-scope decision before canonical heading spans can be selected safely.';whyAdjudicationCannotSafelyContinue='A guessed occurrence universe would conflate structurally independent template labels or reference material.';minimalRecoveryAction='User reviews the source-scope packet or supplies the canonical scope policy.';providerCalls=0;productionModelCalls=0;historicalLevelRead=$false;historicalParentRead=$false})}
Write-Json (Join-Path $out 'blockers.json') @($blockers|ForEach-Object{Read-Json (Join-Path $out "blockers/$($_.docId).json")})
$lines=@('# Canonical deep adjudication batch v3','','Status: **BATCH_V3_READY_FOR_USER_CANONICAL_APPROVAL**','',"Seven new source-backed occurrence → identity → hierarchy proposals are ready for explicit user approval. Four procurement documents remain genuine source-semantic blockers; they are not ordinary review-pending labels.",'','## New proposals')
foreach($r in @($rows|Where-Object status -eq 'READY_FOR_USER_APPROVAL_CANONICAL_HIERARCHY')){$lines += "- **$($r.docId)** — occurrences=$($r.occurrenceCount), semanticNodes=$($r.semanticNodeCount), parentEdges=$($r.parentEdgeCount), ROOT children=$($r.rootChildren), maxDepth=$($r.maxDepth); authority=$($r.proposalAuthority); hierarchy artifact=artifacts/authority-audit/canonical-hierarchy-v3/$($r.docId)/report.md"}
$lines += @('','## Genuine blockers');foreach($r in @($rows|Where-Object status -eq 'GENUINE_HARD_BLOCKER')){$lines += "- **$($r.docId)** — $($r.reasonCode); see blockers/$($r.docId).json"}
$lines += @('','## Firewall','Frozen DOC-0001, DOC-0252, DOC-0256 and DOC-0258 were not mutated. No provider/model calls. Historical level, parent, hierarchy and semantic totals were not read. New authority is AGENT_SOURCE_BACKED_ADJUDICATION and is not USER_REVIEWED_* Gold until explicit approval.')
Write-Text (Join-Path $out 'batch-review.md') ($lines -join "`n")
Write-Json (Join-Path $out 'validation.json') ([ordered]@{artifactKind='A99_CANONICAL_BATCH_V3_VALIDATION';schemaVersion='a99-canonical-batch-v3';status=$summary.status;all11RemainingDocumentsAttempted=$true;frozenExistingUnchanged=($summary.frozenExisting -eq 4);readyForUserApproval=$summary.readyForUserApproval;genuineHardBlockers=$summary.genuineHardBlockers;canonicalGoldMutation=$false;newUserReviewedPromotion=$false;providerCalls=0;productionModelCalls=0;historicalLevelRead=$false;historicalParentRead=$false;historicalHierarchyUsedForDecision=$false;historicalSemanticTotalUsedForDecision=$false})
$files=Get-ChildItem $out -Recurse -File|Sort-Object FullName;Write-Json (Join-Path $out 'manifest.json') ([ordered]@{artifactKind='A99_CANONICAL_BATCH_V3_MANIFEST';schemaVersion='a99-canonical-batch-v3';status=$summary.status;baselineCommit='a5ac90b';deepAdjudication='artifacts/authority-audit/canonical-deep-adjudication-v3/summary.json';generatedArtifacts=@($files|Where-Object Name -ne 'manifest.json'|ForEach-Object{[ordered]@{path=Rel $_.FullName;sha256=Sha $_.FullName}});providerCalls=0;productionModelCalls=0;canonicalGoldMutation=$false;newUserReviewedPromotion=$false})
Write-Output ($summary|ConvertTo-Json -Depth 10)
