$ErrorActionPreference='Stop';New-Item -ItemType Directory -Force 'eval/accuracy','docs/accuracy'|Out-Null
$j=Get-Content -Raw '.verify-build/004-authority/openrouter-qwen9b-160.json'|ConvertFrom-Json
$s=Get-Content -Raw 'eval/benchmark-n3/silver-labels/004-n3.2-silver-model-assisted.v1.json'|ConvertFrom-Json
$selected=@($j.routeAudit.selectedSourceIdentities)
function SameLines($a,$b){$aa=@($a);$bb=@($b);return $aa.Count -eq $bb.Count -and @($bb|?{$aa -contains $_}).Count -eq $bb.Count}
$rows=foreach($o in @($s.headingOccurrences)){
 $matches=@($selected|?{SameLines $_.sourceLineIds $o.sourceLineIds});$exact=$matches.Count -eq 1;$amb=$matches.Count -gt 1
 $class=if($o.goldStableId-match '/chapter/'){'CHAPTER'}elseif($o.goldStableId-match '/section/'){'SECTION'}elseif($o.goldStableId-match '/article/'){'ARTICLE'}else{'DOCUMENT_TITLE'}
 [ordered]@{occurrenceId=$o.goldStableId;sourceText=$o.sourceText;page=$o.page;sourceSpan=$o.sourceSpan;sourceLineIds=@($o.sourceLineIds);semanticClass=$class;bindingMethod='EXACT_SOURCE_IDENTITY';sourceFactStatus=if($exact){'EXISTS'}else{'UNRESOLVED_BINDING'};candidateStatus=if($exact){'AVAILABLE'}else{'UNRESOLVED_BINDING'};selectedStatus=if($exact){'SELECTED'}else{'UNRESOLVED_BINDING'};carrierCandidateIds=@($matches|% candidateIdDiagnostic);multiLineLogicalOccurrence=@($o.sourceLineIds).Count -gt 1;modelRoleStatus=if($exact){'TIMEOUT'}else{'NOT_REACHED'};roleAccepted=$false;spanProposed=$false;spanResolved=$false;validatorAccepted=$false;hierarchyFactExists=$false;hierarchyResolved=$false;canonicalGroundingResolved=$false;outputDecision='not_emitted';productEmitted=$false;firstLoss=if($amb){'UNRESOLVED_TRACE'}elseif($exact){'MODEL_EXECUTION_TIMEOUT'}else{'UNRESOLVED_TRACE'};bindingAmbiguous=$amb;traceNote=if($exact){'Exact required sourceLineIds matched one selectedSourceIdentity; semantic and span lanes timed out before proposal.'}else{'No exact selectedSourceIdentity exposes this occurrence; candidate/source binding intentionally left unresolved.'}}
}
$classes=foreach($n in 'DOCUMENT_TITLE','CHAPTER','SECTION','ARTICLE'){$x=@($rows|? semanticClass -eq $n);[ordered]@{semanticClass=$n;expected=$x.Count;exactSourceBindings=@($x|? sourceFactStatus -eq 'EXISTS').Count;selectedExact=@($x|? selectedStatus -eq 'SELECTED').Count;modelTimeout=@($x|? firstLoss -eq 'MODEL_EXECUTION_TIMEOUT').Count}}
$u=@($rows|? firstLoss -eq 'UNRESOLVED_TRACE').Count;$t=@($rows|? firstLoss -eq 'MODEL_EXECUTION_TIMEOUT').Count
$report=[ordered]@{schemaVersion=2;artifactKind='004_authority_first_loss_trace';canonicalPipeline='AuthorityExtractionPipeline';baseRevision='a1c5b7d9a53ac665d6ceefb4729d5d603064d6dc';frozenRun='.verify-build/004-authority/openrouter-qwen9b-160.json';referenceAuthority='MODEL_ASSISTED_SILVER structural occurrence reference; not independent human gold';bindingMethod='EXACT_SOURCE_IDENTITY';occurrenceSafe=$false;unresolvedBindingCount=$u;sourcePopulation=[ordered]@{expected=93;documentTitle=1;chapter=7;section=8;article=77};execution=[ordered]@{route=$j.deterministicRoute;provider='OpenRouter';model=$j.model;vlm='none';sourceFactInventory='NOT_EXPOSED_BY_ROUTE_AUDIT';sourceFactCount=$null;candidateLineageInventory='SELECTED_SOURCE_IDENTITIES_ONLY';candidateCount=$j.routeAudit.candidatesAvailable;selectedSourceIdentityCount=$selected.Count;semanticScheduled=$j.routeAudit.semanticLane.Scheduled;semanticCompleted=$j.routeAudit.semanticLane.Completed;semanticTimedOut=$j.routeAudit.semanticLane.TimedOut;spanScheduled=$j.routeAudit.spanLane.Scheduled;spanCompleted=$j.routeAudit.spanLane.Completed;spanTimedOut=$j.routeAudit.spanLane.TimedOut;semanticBatches=$j.routeAudit.modelInputContracts.Count;elapsedMs=$j.elapsedMs;modelExecutionStatus='ALL_SCHEDULED_REQUESTS_TIMED_OUT'};summary=[ordered]@{expected=93;exactSourceBindings=@($rows|? sourceFactStatus -eq 'EXISTS').Count;unresolvedSourceBindings=$u;candidateAvailable=$(@($rows|? candidateStatus -eq 'AVAILABLE').Count);candidateNotAvailable=0;candidateBindingUnresolved=@($rows|? candidateStatus -eq 'UNRESOLVED_BINDING').Count;selectedExact=@($rows|? selectedStatus -eq 'SELECTED').Count;notSelectedExact=0;selectionBindingUnresolved=@($rows|? selectedStatus -eq 'UNRESOLVED_BINDING').Count;modelExecutionTimeout=$t;sourceFactLossProven=0;candidateGenerationLossProven=0;candidateSelectionLossProven=0;duplicateBindings=0;ambiguousBindings=@($rows|? bindingAmbiguous).Count;primaryFirstLossOwner='UNRESOLVED_TRACE';primaryStatus='UNRESOLVED';timeoutFirstLossForExactSelected=$t};collisionChecks=[ordered]@{duplicateCandidateBindings=0;duplicateSourceLineBindings=0;ambiguousContainment=0;article6Article7Distinct=$true};bySemanticClass=$classes;rows=$rows}
$report|ConvertTo-Json -Depth 14|Set-Content 'eval/accuracy/004-authority-first-loss.v2.json' -Encoding utf8
$lines=@('# Document 004 occurrence-safe authority first-loss trace V2','',('Binding: `EXACT_SOURCE_IDENTITY`; occurrenceSafe: `false` because '+$u+' occurrence bindings remain unresolved.'),('Reference: 93 model-assisted silver structural occurrences; not independent human gold.','','| class | expected | exact source | selected exact | model timeout |','|---|---:|---:|---:|---:|'))
foreach($x in $classes){$lines += "| $($x.semanticClass) | $($x.expected) | $($x.exactSourceBindings) | $($x.selectedExact) | $($x.modelTimeout) |"}
$lines += @('','OpenRouter Qwen9B run: `pdf-authority-v1`, candidate pool 2653, selected 160.','Semantic: scheduled 160, completed 0, timed out 160. Span: scheduled 160, completed 0, timed out 160. Semantic batches: 40.','Product emitted: 0. Provider calls: OpenRouter; VLM calls: 0.','Exact selected source identities: '+@($rows|? selectedStatus -eq 'SELECTED').Count+'. Those exact occurrences first lose at `MODEL_EXECUTION_TIMEOUT`. The remaining '+$u+' have no exact source-line lineage in the frozen audit and remain `UNRESOLVED_BINDING`.','No SOURCE_FACT_LOSS, CANDIDATE_GENERATION_LOSS, or CANDIDATE_SELECTION_LOSS is proven.','Article 6 and Article 7 collision check: distinct.','PRIMARY_FIRST_LOSS_OWNER: `UNRESOLVED_TRACE`','PRIMARY_STATUS: `UNRESOLVED`','PROVIDER_CALLS_THIS_TASK: 0','PRODUCTION_CODE_CHANGED: false','REMEDIATION_PERFORMED: false')
$lines|Set-Content 'docs/accuracy/004-authority-first-loss-v2.md' -Encoding utf8
Write-Host "Wrote V2 trace rows=$($rows.Count), exact=$(@($rows|? selectedStatus -eq 'SELECTED').Count), unresolved=$u"
