$ErrorActionPreference='Stop'
New-Item -ItemType Directory -Force 'eval/accuracy','docs/accuracy' | Out-Null
$j=Get-Content -Raw '.verify-build/004-authority/openrouter-qwen9b-160.json'|ConvertFrom-Json
$s=Get-Content -Raw 'eval/benchmark-n3/silver-labels/004-n3.2-silver-model-assisted.v1.json'|ConvertFrom-Json
$all=@($j.routeAudit.candidateBlocks);$sel=@($j.routeAudit.selectedCandidateBlocks)
function C([string]$x){if(!$x){return ''};return (($x.ToUpperInvariant()-replace '[^A-Z0-9]+',' ').Trim())}
$rows=foreach($o in @($s.headingOccurrences)){
 $key=(C $o.sourceText)-split ' '|? Length -gt 1|Select-Object -First 3
 $a=$all|?{(C $_.text) -like "*$($key -join '*')*"}|select -First 1
 $b=$sel|?{$a -and $_.id -eq $a.id}
 $class=if($o.goldStableId-match '/chapter/'){'CHAPTER'}elseif($o.goldStableId-match '/section/'){'SECTION'}elseif($o.goldStableId-match '/article/'){'ARTICLE'}else{'DOCUMENT_TITLE'}
 $has=[bool]$a;$chosen=[bool]$b
 [ordered]@{occurrenceId=$o.goldStableId;sourceText=$o.sourceText;sourceSpan=$o.sourceSpan;sourceLineIds=@($o.sourceLineIds);sourceParagraphStableId=if($a){$a.id}else{$null};semanticClass=$class;sourceFactExists=$has;candidateExists=$has;candidateSelected=$chosen;modelRole=if($chosen){'timeout'}else{'not_reached'};roleAccepted=$false;spanProposed=$false;spanResolved=$false;validatorAccepted=$false;hierarchyFactExists=$false;hierarchyResolved=$false;canonicalGroundingResolved=$false;outputDecision='not_emitted';productEmitted=$false;firstLoss=if(!$has){'SOURCE_FACT_LOSS'}elseif(!$chosen){'CANDIDATE_SELECTION_LOSS'}else{'UNRESOLVED_TRACE'};traceNote='OpenRouter Qwen9B PDF authority run: selected semantic requests timed out before role/span completion.'}
}
$classes=foreach($n in 'DOCUMENT_TITLE','CHAPTER','SECTION','ARTICLE'){$x=@($rows|? semanticClass -eq $n);[ordered]@{semanticClass=$n;expected=$x.Count;emitted=0;sourceFact=@($x|? sourceFactExists).Count;candidate=@($x|? candidateExists).Count;selected=@($x|? candidateSelected).Count}}
$loss=[ordered]@{SOURCE_FACT_LOSS=@($rows|? firstLoss -eq 'SOURCE_FACT_LOSS').Count;CANDIDATE_SELECTION_LOSS=@($rows|? firstLoss -eq 'CANDIDATE_SELECTION_LOSS').Count;UNRESOLVED_TRACE=@($rows|? firstLoss -eq 'UNRESOLVED_TRACE').Count;EMITTED=0}
$report=[ordered]@{schemaVersion=1;artifactKind='004_authority_first_loss_trace';canonicalPipeline='AuthorityExtractionPipeline';baseRevision='a1c5b7d9a53ac665d6ceefb4729d5d603064d6dc';referenceAuthority='MODEL_ASSISTED_SILVER structural occurrence reference; not independent human gold';sourcePopulation=[ordered]@{expected=93;documentTitle=1;chapter=7;section=8;article=77};execution=[ordered]@{route=$j.deterministicRoute;provider='OpenRouter';model=$j.model;vlm='none';sourceFacts=$j.routeAudit.candidatesAvailable;candidateCount=$j.routeAudit.candidatesAvailable;candidateSelected=$j.routeAudit.candidatesSelected;modelRequestedParagraphs=$j.routeAudit.semanticLane.Scheduled;semanticBatches=$j.routeAudit.modelInputContracts.Count;spanRequests=$j.routeAudit.spanLane.Scheduled;semanticHierarchyRequests=$j.routeAudit.hierarchyProposals.Count;semanticLane=$j.routeAudit.semanticLane;spanLane=$j.routeAudit.spanLane;elapsedMs=$j.elapsedMs;executionStatus='completed_with_semantic_and_span_timeouts'};summary=[ordered]@{productEmitted=0;bySemanticClass=$classes;firstLossCounts=$loss;primaryFirstLossOwner='UNRESOLVED_TRACE';primaryStatus='UNRESOLVED';secondaryFirstLossOwner='CANDIDATE_SELECTION_LOSS';unresolved=$loss.UNRESOLVED_TRACE};rows=$rows}
$report|ConvertTo-Json -Depth 12|Set-Content 'eval/accuracy/004-authority-first-loss.v1.json' -Encoding utf8
$lines=@('# Document 004 authority first-loss trace','',('Canonical pipeline: `AuthorityExtractionPipeline`'),('Reference: 93 model-assisted silver structural occurrences; not independent human gold.','','| class | expected | emitted | source fact | candidate | selected |','|---|---:|---:|---:|---:|---:|'))
foreach($x in $classes){$lines += "| $($x.semanticClass) | $($x.expected) | 0 | $($x.sourceFact) | $($x.candidate) | $($x.selected) |"}
$lines += @('','Current run: OpenRouter Qwen9B, PDF route, 160 selected blocks. Product emitted: 0.',('Semantic scheduled/completed/timed out: '+$j.routeAudit.semanticLane.Scheduled+'/'+$j.routeAudit.semanticLane.Completed+'/'+$j.routeAudit.semanticLane.TimedOut+'.'),('Span scheduled/completed/timed out: '+$j.routeAudit.spanLane.Scheduled+'/'+$j.routeAudit.spanLane.Completed+'/'+$j.routeAudit.spanLane.TimedOut+'.'),'Provider calls: OpenRouter; VLM calls: 0.','No validator, hierarchy, grounding, or output-policy loss is claimed because model lanes timed out before proposals.','PRIMARY_FIRST_LOSS_OWNER: `UNRESOLVED_TRACE`','STATUS: `UNRESOLVED`','PRODUCTION_CODE_CHANGED: false','REMEDIATION_PERFORMED: false')
$lines|Set-Content 'docs/accuracy/004-authority-first-loss.md' -Encoding utf8
Write-Host "Wrote 004 trace rows=$($rows.Count)"
