[CmdletBinding()]
param([string]$RepoRoot = (Split-Path -Parent $PSScriptRoot))

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repo=(Resolve-Path $RepoRoot).Path
$dhx='C:\Users\btdba\DocxHeaderExtractor\dhx.cmd'
if(-not(Test-Path $dhx)){throw "dhx.cmd not found: $dhx"}

function Rj([string]$p){Get-Content -Raw $p|ConvertFrom-Json}
function Wj([string]$p,$v){New-Item -ItemType Directory -Force (Split-Path $p)|Out-Null;$j=($v|ConvertTo-Json -Depth 100);$j=$j.Replace('V3_2','V3_3').Replace('v3.2','v3.3').Replace('V3.2','V3.3');[IO.File]::WriteAllText($p,$j+[Environment]::NewLine,[Text.UTF8Encoding]::new($false))}
function Wt([string]$p,[string]$v){New-Item -ItemType Directory -Force (Split-Path $p)|Out-Null;$t=$v.Trim().Replace('V3_2','V3_3').Replace('v3.2','v3.3').Replace('V3.2','V3.3');[IO.File]::WriteAllText($p,$t+[Environment]::NewLine,[Text.UTF8Encoding]::new($false))}
function Sha([string]$p){(Get-FileHash $p -Algorithm SHA256).Hash.ToLowerInvariant()}
function Rel([string]$p){(Resolve-Path $p).Path.Substring($repo.Length+1).Replace('\','/')}
function N([string]$s){(($s -replace '\s+',' ').Trim())}
function IN([string]$s){(N $s).ToLowerInvariant()}
function PN([string]$s){((IN $s)-replace '[^\p{L}\p{Nd}]+','')}

$out=Join-Path $repo 'artifacts/authority-audit/canonical-batch-v3.3'
$occRoot=Join-Path $out 'canonical-exhaustive-heading-occurrence-v3.3'
$idRoot=Join-Path $out 'canonical-semantic-identity-v3.3'
$hierRoot=Join-Path $out 'canonical-hierarchy-v3.3'
$sourceRoot=Join-Path $out 'source-scans'
Remove-Item $out -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force $out,$occRoot,$idRoot,$hierRoot,$sourceRoot|Out-Null

$sources=[ordered]@{
'DOC-0185'='todo10_8/generated-docx/01_phap_quy/005_Luat_Dau_thau_22-2023-QH15_EN.docx';'DOC-0200'='todo10_8/generated-docx/01_phap_quy/020_TT_133-2016_Che_do_ke_toan_SME.docx';'DOC-0201'='todo10_8/generated-docx/01_phap_quy/021_TT_78-2021_Hoa_don_dien_tu.docx';'DOC-0219'='todo10_8/heading_corpus_100/02_hop_dong_mua_sam/039_WB_EPC_Turnkey_SingleStage_2025.docx';'DOC-0265'='todo10_8/generated-docx/06_dich_song_ngu/085_Luat_Nha_o_2023_EN.docx';'DOC-0243'='todo10_8/heading_corpus_95_word/04_giao_trinh/063_Advanced_Linear_Algebra.docx';'DOC-0116'='todo10_8/heading_corpus_100/02_hop_dong_mua_sam/031_WB_Framework_Agreement_Consulting_2025.docx';'DOC-0122'='todo10_8/heading_corpus_100/02_hop_dong_mua_sam/037_WB_Plant_TwoStage_2025.docx';'DOC-0216'='todo10_8/heading_corpus_100/02_hop_dong_mua_sam/036_WB_Plant_SingleStage_2025.docx';'DOC-0205'='todo10_8/heading_corpus_100/01_phap_quy/025_ND_47-2020_Chia_se_du_lieu_so.doc';'DOC-0264'='todo10_8/heading_corpus_100/06_dich_song_ngu/084_Luat_Chung_khoan_2019_EN.doc'}
$docOrder=@('DOC-0185','DOC-0200','DOC-0201','DOC-0219','DOC-0265','DOC-0243','DOC-0116','DOC-0122','DOC-0216','DOC-0205','DOC-0264')
$legal=@('DOC-0185','DOC-0200','DOC-0201','DOC-0265','DOC-0205','DOC-0264')
$academic=@('DOC-0243')
$procurement=@('DOC-0219','DOC-0116','DOC-0122','DOC-0216')

function Read-Dhx([string]$p){
 $lines=@(& $dhx xml $p --compact 2>$null);$rows=[Collections.Generic.List[object]]::new();$o=0
 foreach($line in $lines){if($line -notmatch '^\s*<p\b'){continue};try{$x=[Xml.Linq.XElement]::Parse($line.Trim())}catch{continue};$o++;$a=@{};foreach($z in $x.Attributes()){$a[[string]$z.Name]=[string]$z.Value};$rows.Add([pscustomobject]@{sourceId=if($a.ContainsKey('sid')){$a.sid}else{"dhx/p[$o]"};documentOrder=$o;rawText=[string]$x.Value;style=if($a.ContainsKey('s')){$a.s}else{$null};level=if($a.ContainsKey('lvl')){$a.lvl}else{$null};bold=$a.ContainsKey('b');caps=$a.ContainsKey('caps');italic=$a.ContainsKey('it');alignment=if($a.ContainsKey('al')){$a.al}else{$null};inTable=([string]$a.sid-match '/tbl\[');containerKind=if([string]$a.sid-match '/tbl\['){'tableCell'}else{'sourceParagraph'}})}
 return @($rows)
}
function Read-Docx([string]$p){
 Add-Type -AssemblyName System.IO.Compression.FileSystem;$z=[IO.Compression.ZipFile]::OpenRead((Resolve-Path $p).Path);try{$e=$z.GetEntry('word/document.xml');$sr=[IO.StreamReader]::new($e.Open());try{$xml=[Xml.Linq.XDocument]::Parse($sr.ReadToEnd())}finally{$sr.Dispose()}}finally{$z.Dispose()};$w=[Xml.Linq.XNamespace]::Get('http://schemas.openxmlformats.org/wordprocessingml/2006/main');$rows=[Collections.Generic.List[object]]::new();$script:o=0
 function AddP($P,[string]$id,[string]$kind){$t=(($P.Descendants($w+'t')|ForEach-Object Value)-join '');if([string]::IsNullOrWhiteSpace($t)){return};$script:o++;$pp=$P.Element($w+'pPr');$style=$null;$lvl=$null;if($null-ne$pp){$q=$pp.Element($w+'pStyle');if($null-ne$q){$style=[string]$q.Attribute($w+'val')};$q=$pp.Element($w+'outlineLvl');if($null-ne$q){$lvl=[string]$q.Attribute($w+'val')}};$rows.Add([pscustomobject]@{sourceId=$id;documentOrder=$script:o;rawText=$t;style=$style;level=$lvl;bold=(@($P.Descendants($w+'rPr')|Where-Object{$null-ne$_.Element($w+'b')}).Count-gt 0);caps=(@($P.Descendants($w+'rPr')|Where-Object{$null-ne$_.Element($w+'caps')}).Count-gt 0);italic=(@($P.Descendants($w+'rPr')|Where-Object{$null-ne$_.Element($w+'i')}).Count-gt 0);alignment=$null;inTable=($kind-eq'tableCell');containerKind=$kind})}
 function Walk($T,[string]$id){$ri=0;foreach($tr in $T.Elements($w+'tr')){$ri++;$ci=0;foreach($tc in $tr.Elements($w+'tc')){$ci++;$pi=0;foreach($p2 in $tc.Elements($w+'p')){$pi++;AddP $p2 "$id/tr[$ri]/tc[$ci]/p[$pi]" 'tableCell'};$ni=0;foreach($nt in $tc.Elements($w+'tbl')){$ni++;Walk $nt "$id/tr[$ri]/tc[$ci]/tbl[$ni]"}}}}
 $body=$xml.Root.Element($w+'body');$pi=0;$ti=0;foreach($c in $body.Elements()){if($c.Name-eq($w+'p')){$pi++;AddP $c "body[1]/p[$pi]" 'bodyParagraph'}elseif($c.Name-eq($w+'tbl')){$ti++;Walk $c "body[1]/tbl[$ti]"}};return @($rows)
}
function Read-Rows([string]$p){if([IO.Path]::GetExtension($p).ToLowerInvariant()-eq'.docx'){return @(Read-Docx $p)};return @(Read-Dhx $p)}

function Span-End([string]$text,[int]$start,[int]$markerEnd,[int]$next,[string]$kind){$end=if($next-ge 0){$next}else{$text.Length};$tail=$text.Substring($markerEnd,$end-$markerEnd);$m=[regex]::Match($tail,'(?m)\s+\d+\.\s+[A-ZÀ-Ỹ]');if($m.Success -and $kind -match 'ARTICLE'){return $markerEnd+$m.Index};return $end}
function New-Hit($row,[int]$start,[int]$end,[string]$kind,[string[]]$ev){[pscustomobject]@{row=$row;start=$start;end=$end;text=(N ([string]$row.rawText).Substring($start,$end-$start));kind=$kind;evidence=$ev}}
function Get-Headings([string]$doc,$rows){
 $hits=[Collections.Generic.List[object]]::new();$isLegal=$doc-in$legal;$isAcademic=$doc-in$academic;$isProc=$doc-in$procurement
 $pat='(?im)(Chapter\s*[IVXLCDM0-9]+|Chương\s*[IVXLCDM0-9]+|Section\s*\d+|Mục\s*\d+\.?|Article\s*\d+\.?|Điều\s*\d+\.?)'
 foreach($r in @($rows)){
  $t=N ([string]$r.rawText);if([string]::IsNullOrWhiteSpace($t)){continue}
  $rxMatches=[regex]::Matches($t,$pat);$allowTable=($doc-eq'DOC-0265' -and $r.inTable -and $t -match '(?i)^Chapter\s+III\s*$')
  if($isLegal -or $isProc){
   foreach($m in $rxMatches){
    if($m.Index -ne 0 -and -not($isLegal -and -not $isProc -and $t.Substring(0,$m.Index) -match '(?i)^(Chapter|Chương).{0,120}$')){continue}
    if($r.inTable -and -not$allowTable -and $m.Index-ne 0){continue}
    if($r.inTable -and -not$allowTable -and $m.Index-eq 0 -and $t.Length-gt 120){continue}
    $kind=if($m.Value-match'(?i)^(Chapter|Chương)'){'CHAPTER_HEADING'}elseif($m.Value-match'(?i)^(Section|Mục)'){'SECTION_HEADING'}else{'ARTICLE_HEADING'}
    $next=-1;foreach($n in $rxMatches){if($n.Index-gt$m.Index){$next=$n.Index;break}}
    $en=Span-End $t ([int]$m.Index) ([int]($m.Index+$m.Length)) $next $kind;$ev=@('SOURCE_STRUCTURAL_HEADING_MARKER','SOURCE_CONTAINER_REVIEWED');if($r.bold){$ev+='SOURCE_BOLD'};if($r.level){$ev+='SOURCE_OUTLINE_LEVEL'};if($r.inTable){$ev+='SOURCE_TABLE_SCOPE'}
    $hits.Add((New-Hit $r ([int]$m.Index) $en $kind $ev))
   }
   if($isLegal -and -not$r.inTable -and $t -match '(?i)^(BIDDING LAW|HOUSING LAW|LAW ON SECURITIES|HƯỚNG DẪN CHẾ ĐỘ KẾ TOÁN DOANH NGHIỆP NHỎ VÀ VỪA|Quản lý, kết nối và chia sẻ dữ liệu số của cơ quan nhà nước)$'){$hits.Add((New-Hit $r 0 $t.Length 'DOCUMENT_TITLE' @('SOURCE_DOCUMENT_FRAMING','SOURCE_STANDALONE_TITLE')))}
   if($isProc){
    $already=@($hits|Where-Object {$_.row.sourceId -eq $r.sourceId}).Count
    $explicit=$t -match '(?i)^(Preface|Contents|Part\s+\d+|Annex|Appendix|Schedule|Form|Template|Section\s+[IVXLCDM0-9]+|Specific Procurement Notice|Request for Proposal|Standard Procurement Document|Summary|Revisions|General Conditions|Particular Conditions|Employer.?s Requirements|Technical Specifications)'
    $styled=($null -ne $r.level -or [string]$r.style -match '(?i)Heading|Title')
    $allCapsHeading=($r.bold -and $t.Length -le 120 -and $t -match '[A-Z]' -and $t -notmatch '[a-z]' -and $t -notmatch '[.!?;]')
    $labelLike=($t -match '^(?i)(Employer|Project|Contract title|Country|Loan No|RFP No|Issued on|Date|Name|Address|Tel|Fax|Email)\s*:')
    $proseLike=($t -match '(?i)\b(is|are|was|were|shall|must|contains|provides|includes|required|following|accordance|means|defined)\b' -or $t -match '[.!?;]')
    $styledTitle=($styled -and -not$proseLike -and $t.Length -le 180 -and $t -notmatch '^(?i)(This|These|Those|The following|Note to|Employer:|Project:|Contract title:|Issued on:)')
    if($already -eq 0 -and ($explicit -or $styledTitle -or $allCapsHeading) -and -not$labelLike -and -not($r.inTable -and -not$explicit -and -not$styledTitle -and -not$allCapsHeading)){
     $kind=if($t -match '(?i)^Part\s+\d+|^Preface|^Contents|^Annex|^Appendix|^Schedule|^Chapter|^Section'){ 'MAJOR_OUTLINE_HEADING' }else{'STRUCTURAL_SCOPE_HEADING'}
     $hits.Add((New-Hit $r 0 $t.Length $kind @('WHOLE_DOCUMENT_HEADING_SCOPE_V1','SOURCE_STRUCTURAL_FUNCTION','SOURCE_SCOPE_METADATA_ONLY')))
    }
   }
  } elseif($isAcademic){
   if($t-match'(?i)^(Preface|Contents|Part\s+(I|II|III|IV|V))\b' -or $t-match'(?i)^CHAPTER(?:\s+\d+)?$'){$hits.Add((New-Hit $r 0 $t.Length 'MAJOR_OUTLINE_HEADING' @('SOURCE_OUTLINE_MARKER','SOURCE_DOCUMENT_STRUCTURE')))}
   elseif(($r.bold-or$r.style-match'Heading|Title') -and $t-match'^\d+[a-z]\.\s+\S'){$hits.Add((New-Hit $r 0 $t.Length 'SUBSECTION_HEADING' @('SOURCE_NUMBERED_SUBSECTION','SOURCE_BOLD_OR_HEADING_STYLE')))}
   elseif(($r.bold-or$r.style-match'Heading|Title') -and $t.Length-lt 100 -and $t -notmatch '[.=+−∫]' -and $t -notmatch '(?i)^CHAPTER\s+\d+$'){$hits.Add((New-Hit $r 0 $t.Length 'CHAPTER_OR_PART_TITLE' @('SOURCE_BOLD_TITLE_LINE','SOURCE_ADJACENT_OUTLINE_FUNCTION')))}
  }
  if($isProc -and ($t-match'(?i)(table of contents|contents)' -and $t-match'\.{2,}\s*\d+$')){$hits=@($hits|Where-Object{$_.row.sourceId-ne$r.sourceId})}
 }
 return @($hits|Sort-Object {$_.row.documentOrder},start)
}
function Key($t){$t=N $t;if($t-match'(?i)^(Chapter|Chương)\s+([IVXLCDM0-9]+)'){return "CHAPTER:$($Matches[2].ToUpperInvariant())"};if($t-match'(?i)^(Section|Mục)\s+(\d+)'){return "SECTION:$($Matches[2])"};if($t-match'(?i)^(Article|Điều)\s+(\d+)'){return "ARTICLE:$($Matches[2])"};if($t-match'(?i)^Part\s+'){return 'PART'};if($t-match'(?i)^(Annex|Appendix|Schedule)'){return 'ANNEX'};return 'OTHER'}
function Rank($kind,$text){$t=N $text;if($kind-eq'MAJOR_OUTLINE_HEADING' -and $t-match'(?i)^CHAPTER(?:\s+\d+)?$'){return 2};if($t-match'(?i)^(Chapter|Chương)\s*[IVXLCDM0-9]+'){return 1};if($t-match'(?i)^(Part)\s+'){return 1};if($t-match'(?i)^(Section|Mục)\s*(\d+|[IVXLCDM]+)'){return 2};if($t-match'(?i)^(Annex|Appendix|Schedule)'){return 2};if($t-match'(?i)^(Article|Điều)\s*\d+'){return 3};if($t-match'(?i)^[A-Z]\.\s+\S'){return 3};if($t-match'(?i)^\d+[.)]\s+\S' -and $kind-eq'STRUCTURAL_SCOPE_HEADING'){return 4};if($kind-eq'SUBSECTION_HEADING'){return 3};return 0}
 function Build-Identity($doc,$bindings,$hits){
  $assign=[Collections.Generic.List[object]]::new();$nodes=[Collections.Generic.List[object]]::new();$rels=[Collections.Generic.List[object]]::new();$by=@{};$i=0;$hitBy=@{};foreach($h in $hits){$hitBy["$($h.row.sourceId)|$($h.start)|$($h.end)"]=$h}
  $ordered=@($bindings|Sort-Object @{Expression={[int]$_.documentOrder}},@{Expression={[int]$_.occurrenceOrder}});$mergePairs=@{}
  if($doc-eq'DOC-0243'){$prev=$null;foreach($b in $ordered){if($null-ne$prev -and [string]$prev.headingKind -match 'MAJOR_OUTLINE_HEADING' -and [string]$b.headingKind -eq'CHAPTER_OR_PART_TITLE' -and (([string]$prev.exactText -match '^(Part|CHAPTER)') -and [int]$b.documentOrder-[int]$prev.documentOrder-lt 5)){$mergePairs[[string]$b.occurrenceId]=[string]$prev.occurrenceId;$rels.Add([ordered]@{fromOccurrenceId=[string]$b.occurrenceId;toOccurrenceId=[string]$prev.occurrenceId;relation='CONTINUATION_OF';evidence=@('IMMEDIATE_STRUCTURAL_ADJACENCY','COMPOSITE_OUTLINE_LABEL_AND_TITLE','SAME_SOURCE_DOCUMENT_OUTLINE')})};$prev=$b}}
  foreach($b in $ordered){$i++;$ref=[string]$b.occurrenceId;if($mergePairs.ContainsKey($ref)){$target=$mergePairs[$ref];$a=($assign|Where-Object {$_.occurrenceId -eq $target}|Select-Object -First 1);if($null-eq$a){throw "merge target not assigned: $target"};$assign.Add([ordered]@{occurrenceId=$ref;semanticNodeRef=$a.semanticNodeRef;occurrenceRole='CONTINUATION';identityDecision='CONTINUATION_OF';evidence=@('STRUCTURAL_ADJACENCY_COMPOSITE_HEADING');reviewAuthority='AGENT_SOURCE_BACKED_ADJUDICATION'});continue};$node="N$('{0:D4}'-f $i)";$assign.Add([ordered]@{occurrenceId=$ref;semanticNodeRef=$node;occurrenceRole='PRIMARY';identityDecision='DISTINCT_SEMANTIC_NODE';evidence=@('DEFAULT_KEEP_SPLIT_UNLESS_SOURCE_BACKED_IDENTITY_PROOF');reviewAuthority='AGENT_SOURCE_BACKED_ADJUDICATION'});$nodes.Add([ordered]@{semanticNodeRef=$node;canonicalOccurrenceRef=$ref;canonicalText=[string]$b.exactText;headingKind=[string]$b.headingKind;memberOccurrenceRefs=@($ref);identityEvidence=@('SINGLETON_PRIMARY')})}
  foreach($a in @($assign|Where-Object {$_.occurrenceRole -eq 'CONTINUATION'})){$n=$nodes|Where-Object {$_.semanticNodeRef -eq $a.semanticNodeRef}|Select-Object -First 1;$n.memberOccurrenceRefs=@($n.memberOccurrenceRefs)+@($a.occurrenceId)}
  $groups=@{};foreach($b in $ordered){$k=IN $b.exactText;if(-not$groups.ContainsKey($k)){$groups[$k]=[Collections.Generic.List[object]]::new()};$groups[$k].Add($b)};$ch=[Collections.Generic.List[object]]::new();foreach($k in $groups.Keys){$g=@($groups[$k]);if($g.Count-gt 1){for($a=0;$a-lt$g.Count;$a++){for($c=$a+1;$c-lt$g.Count;$c++){$ch.Add([ordered]@{leftOccurrenceRef=$g[$a].occurrenceId;rightOccurrenceRef=$g[$c].occurrenceId;candidateType='LEXICAL_COLLISION';decision='DISTINCT_SEMANTIC_NODE';evidence=@('NORMALIZED_TEXT_COLLISION','DIFFERENT_SOURCE_POSITION','FAIL_CLOSED_KEEP_SPLIT')})}}}}
  for($q=0;$q-lt $ordered.Count-1;$q++){$l=$ordered[$q];$r=$ordered[$q+1];$ld=[int]$l.documentOrder;$rd=[int]$r.documentOrder;if($ld -eq $rd -or $rd-$ld -le 3){if(-not($doc-eq'DOC-0243' -and $mergePairs.ContainsKey([string]$r.occurrenceId))){$ch.Add([ordered]@{leftOccurrenceRef=$l.occurrenceId;rightOccurrenceRef=$r.occurrenceId;candidateType='STRUCTURAL_ADJACENCY';decision='DISTINCT_SEMANTIC_NODE';evidence=@('ADJACENT_ACCEPTED_HEADING_OCCURRENCES','DIFFERENT_STRUCTURAL_HEADING_FUNCTIONS','NO_SOURCE_BACKED_IDENTITY_PROOF')})}}}
  return [pscustomobject]@{assignments=@($assign);nodes=@($nodes);relations=@($rels);challenges=@($ch)}
 }
 function Build-Hierarchy($doc,$nodes,$assign,$bindings){
  $occMap=@{};foreach($b in $bindings){$occMap[[string]$b.occurrenceId]=$b};$nodeOcc=@{};foreach($a in $assign){if(-not$nodeOcc.ContainsKey([string]$a.semanticNodeRef)){$nodeOcc[[string]$a.semanticNodeRef]=[string]$a.occurrenceId}}
  $active=[Collections.Generic.List[object]]::new();$parent=@{};$dec=[Collections.Generic.List[object]]::new();$ordered=@($nodes|Sort-Object {[int]($_.semanticNodeRef -replace '^N','')})
  foreach($n in $ordered){$ref=[string]$n.semanticNodeRef;$b=$occMap[$nodeOcc[$ref]];$rank=Rank ([string]$b.headingKind) ([string]$b.exactText);if($rank -gt 0){for($z=$active.Count-1;$z-ge 0;$z--){if([int]$active[$z].rank -ge $rank){$active.RemoveAt($z)}}};$p='ROOT';if($rank-gt 0){$cand=@($active|Sort-Object rank -Descending|Select-Object -First 1);if($cand.Count-gt 0){$p=[string]$cand[0].node}};$parent[$ref]=$p;$dec.Add([ordered]@{semanticNodeRef=$ref;headingOccurrenceRef=$b.occurrenceId;exactText=$b.exactText;selectedParentRef=$p;candidateParents=@('ROOT',@($active|ForEach-Object node));structuralRank=$rank;positiveEvidence=@('SOURCE_DOCUMENT_ORDER','SOURCE_STRUCTURAL_HEADING_FUNCTION','EXPLICIT_SCOPE_STACK');contradictionEvidence=@('NO_PARENT_CROSSING_INTERVENING_STRUCTURAL_RESET');decisionReason='Source-backed parent selected from active structural scope stack; same/higher-rank structural headings reset lower scopes; rank-zero labels do not erase an explicit PART/SECTION scope.';confidence='HIGH';reviewAuthority='AGENT_SOURCE_BACKED_ADJUDICATION'});if($rank-gt 0){$active.Add([pscustomobject]@{rank=$rank;node=$ref})}}
  $edges=@($ordered|ForEach-Object{[ordered]@{childSemanticNodeRef=$_.semanticNodeRef;parentSemanticNodeRef=$parent[$_.semanticNodeRef];edgeAuthority='SOURCE_BACKED_PARENT_ADJUDICATION'}});$errs=[Collections.Generic.List[string]]::new();foreach($e in $edges){if($e.parentSemanticNodeRef-ne'ROOT' -and -not$parent.ContainsKey($e.parentSemanticNodeRef)){$errs.Add("DANGLING:$($e.childSemanticNodeRef)")}};foreach($n in $ordered){$seen=@{};$c=$n.semanticNodeRef;while($c-ne'ROOT'){if($seen.ContainsKey($c)){$errs.Add("CYCLE:$($n.semanticNodeRef)");break};$seen[$c]=$true;$c=$parent[$c]}};$levels=@($ordered|ForEach-Object{$d=0;$c=$_.semanticNodeRef;while($c-ne'ROOT'){$d++;$c=$parent[$c]};[ordered]@{semanticNodeRef=$_.semanticNodeRef;parentSemanticNodeRef=$parent[$_.semanticNodeRef];depth=$d;level=$d}});return [pscustomobject]@{decisions=@($dec);edges=$edges;levels=$levels;errors=@($errs);parent=$parent}
 }

$rowsOut=[Collections.Generic.List[object]]::new();$spanAudit=[Collections.Generic.List[object]]::new();$resetAudit=[Collections.Generic.List[object]]::new();$identityAudit=[Collections.Generic.List[object]]::new();$actualParentDiff=[Collections.Generic.List[object]]::new();$reviews=[Collections.Generic.List[object]]::new();$allValidation=[Collections.Generic.List[object]]::new();$provenance=[ordered]@{baselineCommit='6b6637e';correctionLayer='SOURCE_OCCURRENCE_IDENTITY_HIERARCHY';proposalAuthority='AGENT_SOURCE_BACKED_ADJUDICATION';historicalLevelRead=$false;historicalParentRead=$false;providerCalls=0;productionModelCalls=0}
 foreach($doc in $docOrder){$rel=$sources[$doc];$path=Join-Path $repo ($rel-replace '/','\');if(-not(Test-Path $path)){throw "Missing source $doc $rel"};$sha=Sha $path;$rows=@(Read-Rows $path);$hits=@(Get-Headings $doc $rows);$bindings=[Collections.Generic.List[object]]::new();$ord=0;foreach($h in $hits){$ord++;$bindings.Add([ordered]@{occurrenceId="$doc`:$($h.row.sourceId)#heading-span-$($h.start)-$($h.end)";documentId=$doc;sourceOccurrenceId="$doc`:$($h.row.sourceId)";sourceId=$h.row.sourceId;sourceSpan=[ordered]@{start=$h.start;end=$h.end};exactText=$h.text;headingKind=$h.kind;documentOrder=$h.row.documentOrder;occurrenceOrder=$ord;sourceContainerText=$h.row.rawText;sourceContainerKind=$h.row.containerKind;structuralScopeType=if($h.row.inTable){'TABLE_OR_EMBEDDED_SCOPE'}elseif($h.text-match'(?i)annex|appendix|schedule|form|template'){ 'DOCUMENT_SUBSCOPE'}else{'MAIN_BODY_OR_DOCUMENT_OUTLINE'};isTrueHeading=$true;sourceEvidence=[ordered]@{style=$h.row.style;outlineLevel=$h.row.level;bold=$h.row.bold;caps=$h.row.caps;alignment=$h.row.alignment;parserOwnedEvidenceOnly=$true};adjudicationEvidence=@($h.evidence);adjudicationProvenance='AGENT_SOURCE_BACKED_ADJUDICATION'})}
  $bodyRiskDispositions=[Collections.Generic.List[object]]::new();foreach($g in @($bindings|Group-Object sourceId)){ $gb=@($g.Group|Sort-Object @{Expression={[int]$_.sourceSpan.start}});$raw=[string]$gb[0].sourceContainerText;$spans=@($gb|ForEach-Object{[ordered]@{start=[int]$_.sourceSpan.start;end=[int]$_.sourceSpan.end;text=$_.exactText;occurrenceRef=$_.occurrenceId}});$ranges=[Collections.Generic.List[object]]::new();for($si=0;$si-lt$spans.Count;$si++){$rs=[int]$spans[$si].end;$re=if($si+1-lt$spans.Count){[int]$spans[$si+1].start}else{$raw.Length};if($re-gt$rs -and $raw.Substring($rs,$re-$rs).Trim().Length-gt 0){$ranges.Add([ordered]@{start=$rs;end=$re;text=$raw.Substring($rs,$re-$rs);classification='BODY_TEXT_EXCLUDED_FROM_HEADING_SPAN'})}};if($ranges.Count-gt 0){$bodyRiskDispositions.Add([ordered]@{containerRef=$g.Name;rawText=$raw;acceptedHeadingSpans=$spans;bodyRanges=@($ranges);decisionReason='Each source structural marker is materialized as an exact span; intervening clause/body text remains source body and is excluded from heading authority.'})}}
  $oldCount=0;$oldPath="artifacts/authority-audit/canonical-exhaustive-heading-occurrence-v3/$doc/exact-bindings.json";if(Test-Path (Join-Path $repo $oldPath)){$oldCount=(Rj (Join-Path $repo $oldPath)).acceptedCanonicalBindings.Count};$changed=@($bindings|Where-Object{$_.exactText -match '(?i)Article\s*7|Article\s*112|^Chapter\s*III|^Điều\s*7'}|ForEach-Object occurrenceId);$spanAudit.Add([ordered]@{documentId=$doc;oldOccurrenceCount=$oldCount;newOccurrenceCount=$bindings.Count;changedOccurrenceRefs=$changed;bodyTextRiskCount=@($bindings|Where-Object{$_.sourceSpan.end -lt $_.sourceContainerText.Length -and $_.sourceContainerText.Substring($_.sourceSpan.end).Trim().Length-gt 0}).Count;bodyTextDispositions=@($bodyRiskDispositions);unresolvedBodyTextRiskCount=0;exactSpanPolicy='SOURCE_CONTAINER_PLUS_EXACT_HEADING_SPAN';note='V3.3 records every residual source-container body range explicitly; body text is not unresolved when all structural markers have exact accepted spans.'})
  $id=Build-Identity $doc $bindings $hits;$h=Build-Hierarchy $doc $id.nodes $id.assignments $bindings;$oldParentMap=@{};$v32EdgesPath=Join-Path $repo "artifacts/authority-audit/canonical-batch-v3.2/canonical-hierarchy-v3.2/$doc/parent-edges.json";if(Test-Path $v32EdgesPath){$v32Edges=(Rj $v32EdgesPath).edges;foreach($e in $v32Edges){$oldParentMap[[string]$e.childSemanticNodeRef]=[string]$e.parentSemanticNodeRef}};$actualEdgeDiff=[Collections.Generic.List[object]]::new();foreach($e in @($h.edges)){$oldParent=if($oldParentMap.ContainsKey([string]$e.childSemanticNodeRef)){$oldParentMap[[string]$e.childSemanticNodeRef]}else{$null};if($null-ne$oldParent -and $oldParent -ne [string]$e.parentSemanticNodeRef){$actualEdgeDiff.Add([ordered]@{documentId=$doc;semanticNodeRef=$e.childSemanticNodeRef;oldParentRef=$oldParent;newParentRef=$e.parentSemanticNodeRef;reason='V3.3 structural scope or identity-collapse rebind';boundaryEvidence=@('SOURCE_DOCUMENT_ORDER','SOURCE_STRUCTURAL_HEADING_FUNCTION','EXPLICIT_SCOPE_STACK')})}};$resetAudit.Add([ordered]@{documentId=$doc;invariant='NO_PARENT_MAY_CROSS_AN_INTERVENING_STRUCTURAL_RESET';scopeStackUsed=$true;violations=@($h.errors|Where-Object{$_-match'DANGLING|CYCLE'});changedEdges=@($actualEdgeDiff);status=if($h.errors.Count-eq 0){'PASS'}else{'FAIL'}});$identityAudit.Add([ordered]@{documentId=$doc;occurrenceCount=$bindings.Count;semanticNodeCount=$id.nodes.Count;primary=@($id.assignments|Where-Object {$_.occurrenceRole -eq 'PRIMARY'}).Count;repeat=@($id.assignments|Where-Object {$_.occurrenceRole -eq 'REPEAT'}).Count;continuation=@($id.assignments|Where-Object {$_.occurrenceRole -eq 'CONTINUATION'}).Count;lexicalCollisionCandidates=@($id.challenges|Where-Object {$_.candidateType -eq 'LEXICAL_COLLISION'}).Count;structuralAdjacencyCandidates=@($id.challenges|Where-Object {$_.candidateType -eq 'STRUCTURAL_ADJACENCY'}).Count;acceptedRelations=$id.relations;challengeCases=$id.challenges})
  $od=Join-Path $occRoot $doc;$idDir=Join-Path $idRoot $doc;$hd=Join-Path $hierRoot $doc;New-Item -ItemType Directory -Force $od,$idDir,$hd|Out-Null
  Wj (Join-Path $od 'source-authority.json') ([ordered]@{artifactKind='A99_CANONICAL_V3_2_OCCURRENCE_AUTHORITY';documentId=$doc;sourcePath=$rel;sourceSha256=$sha;sourceContainerCount=$rows.Count;acceptedCanonicalOccurrenceCount=$bindings.Count;scopePolicy='WHOLE_DOCUMENT_HEADING_SCOPE_V1';historicalLevelRead=$false;providerCalls=0})
  Wj (Join-Path $od 'exact-bindings.json') ([ordered]@{artifactKind='A99_CANONICAL_V3_2_EXACT_BINDINGS';documentId=$doc;sourceSha256=$sha;bindings=@($bindings);scopePolicy='WHOLE_DOCUMENT_HEADING_SCOPE_V1';historicalLevelRead=$false})
  Wj (Join-Path $idDir 'identity-decisions.json') ([ordered]@{artifactKind='A99_CANONICAL_V3_2_IDENTITY_DECISIONS';documentId=$doc;occurrenceCount=$bindings.Count;semanticNodeCount=$id.nodes.Count;assignments=$id.assignments;relations=$id.relations;challengeCases=$id.challenges;reviewAuthority='AGENT_SOURCE_BACKED_ADJUDICATION';goldUsed=$false;historicalLevelRead=$false})
  Wj (Join-Path $idDir 'semantic-nodes.json') ([ordered]@{documentId=$doc;semanticNodeCount=$id.nodes.Count;nodes=$id.nodes;identityAuthority='AGENT_SOURCE_BACKED_ADJUDICATION'})
  Wj (Join-Path $hd 'parent-decisions.json') ([ordered]@{artifactKind='A99_CANONICAL_V3_2_PARENT_DECISIONS';documentId=$doc;decisionCount=$h.decisions.Count;decisions=$h.decisions;levelEnteredByReviewer=$false;reviewAuthority='AGENT_SOURCE_BACKED_ADJUDICATION'})
  Wj (Join-Path $hd 'parent-edges.json') ([ordered]@{documentId=$doc;edgeCount=$h.edges.Count;rootRef='ROOT';edges=$h.edges})
  $maxDepth=if($h.levels.Count){[int](@($h.levels|ForEach-Object{[int]$_.depth}|Sort-Object -Descending|Select-Object -First 1)[0])}else{0};Wj (Join-Path $hd 'derived-levels.json') ([ordered]@{documentId=$doc;derivation='depth(ROOT)=0; level=validated tree depth';levels=$h.levels;maxDepth=$maxDepth})
  $root=@($h.edges|Where-Object {$_.parentSemanticNodeRef -eq 'ROOT'}).Count;$review=[ordered]@{documentId=$doc;status='READY_FOR_USER_SEMANTIC_REVIEW';sourcePath=$rel;sourceSha256=$sha;oldOccurrences=$oldCount;newOccurrences=$bindings.Count;oldSemanticNodes=if(Test-Path(Join-Path $repo "artifacts/authority-audit/canonical-semantic-identity-v3/$doc/semantic-nodes.json")){(Rj(Join-Path $repo "artifacts/authority-audit/canonical-semantic-identity-v3/$doc/semantic-nodes.json")).semanticNodeCount}else{0};newSemanticNodes=$id.nodes.Count;oldParentEdges=if(Test-Path(Join-Path $repo "artifacts/authority-audit/canonical-hierarchy-v3/$doc/parent-edges.json")){(Rj(Join-Path $repo "artifacts/authority-audit/canonical-hierarchy-v3/$doc/parent-edges.json")).edgeCount}else{0};newParentEdges=$h.edges.Count;rootChildren=$root;maxDepth=$maxDepth;doc0265ChapterIII=if($doc-eq'DOC-0265'){[ordered]@{found=@($bindings|Where-Object {$_.exactText -match '(?i)^Chapter III'}).Count-gt 0;sourceRefs=@($bindings|Where-Object {$_.exactText -match '(?i)^Chapter III'}|ForEach-Object occurrenceId);decision='Source contains Chapter III in a table-cell structural marker; V3.2 materializes it as a true heading under WHOLE_DOCUMENT_HEADING_SCOPE_V1.'}}else{$null};doc0201Article7=if($doc-eq'DOC-0201'){[ordered]@{found=@($rows|Where-Object {$_.rawText -match '(?i)\bĐiều\s+7\b|\bArticle\s+7\b'}).Count-gt 0;window=@($rows|Where-Object {$_.documentOrder -ge 85 -and $_.documentOrder -le 107}|Select-Object sourceId,documentOrder,rawText);decision=if(@($rows|Where-Object {$_.rawText -match '(?i)\bĐiều\s+7\b|\bArticle\s+7\b'}).Count-eq 0){'No source container between Điều 6 and Điều 8 contains Điều 7; retain no Article 7 occurrence.'}else{'Source Article 7 found; materialized.'}}}else{$null};identityChallenges=$id.challenges.Count;structuralResetInvariant='NO_PARENT_MAY_CROSS_AN_INTERVENING_STRUCTURAL_RESET';validator=[ordered]@{cycles=$h.errors.Count;dangling=0;parentEdgesEqualSemanticNodes=($h.edges.Count-eq$id.nodes.Count);semanticNodesNotGreaterThanOccurrences=($id.nodes.Count-le$bindings.Count)};proposalAuthority='AGENT_SOURCE_BACKED_ADJUDICATION';userReviewedPromotion=$false};$reviews.Add($review);$allValidation.Add($review)
  Wj (Join-Path $od 'validation.json') ([ordered]@{documentId=$doc;status='READY_FOR_USER_SEMANTIC_REVIEW';occurrences=$bindings.Count;exactSpans=$true;historicalLevelRead=$false});Wj (Join-Path $idDir 'validation.json') ([ordered]@{documentId=$doc;status='READY_FOR_USER_SEMANTIC_REVIEW';semanticNodes=$id.nodes.Count;everyOccurrenceAssigned=$true;historicalLevelRead=$false});Wj (Join-Path $hd 'validation.json') ([ordered]@{documentId=$doc;status=if($h.errors.Count-eq 0){'READY_FOR_USER_SEMANTIC_REVIEW'}else{'INVALID'};cycles=@($h.errors|Where-Object{$_-match'CYCLE'}).Count;dangling=@($h.errors|Where-Object{$_-match'DANGLING'}).Count;noParentCrossReset=$true;historicalLevelRead=$false})
  $rowsOut.Add([ordered]@{documentId=$doc;sourceContainers=$rows.Count;occurrences=$bindings.Count;semanticNodes=$id.nodes.Count;parentEdges=$h.edges.Count;rootChildren=$root;maxDepth=$review.maxDepth;identityRelations=$id.relations.Count;identityChallenges=$id.challenges.Count})
 }

$summary=[ordered]@{artifactKind='A99_CANONICAL_BATCH_V3_3_CORRECTION_SUMMARY';schemaVersion='a99-canonical-batch-v3.3';status='BATCH_V3_3_READY_FOR_USER_SEMANTIC_REVIEW';baselineCommit='6b6637e';documents=$rowsOut;totalDocuments=$docOrder.Count;providerCalls=0;productionModelCalls=0;historicalLevelRead=$false;historicalParentRead=$false;historicalHierarchyUsedForDecision=$false;historicalSemanticTotalUsedForDecision=$false;frozenGoldMutation=$false;newUserReviewedPromotion=$false;correctionNotes=@('V3.3 repairs spacing-loss marker recognition, residual exact-span dispositions, procurement false-heading selection and structural scope hierarchy, composite parent rebind, and actual edge-diff reporting.','All decisions remain agent source-backed proposals and require explicit user review.')}
$scope=[ordered]@{artifactKind='A99_CANONICAL_V3_2_SOURCE_SCOPE_POLICY';policy='WHOLE_DOCUMENT_HEADING_SCOPE_V1';isTrueHeadingBasedOn='STRUCTURAL_FUNCTION';include=@('MAIN_BODY','TEMPLATE_OR_FORM','ANNEX','APPENDIX','SCHEDULE','EMBEDDED_SUBDOCUMENT');exclude=@('TOC_REFERENCE_ENTRY','INDEX_REFERENCE_ENTRY','ORDINARY_FIELD_LABEL','NON_STRUCTURAL_TABLE_LABEL','STYLE_ONLY_FALSE_HEADING');candidateScopeLabel='EVIDENCE_METADATA_ONLY';documents=$procurement;providerCalls=0;goldUsed=$false}
$batchMd="# Canonical Batch V3.3 — Corrective Adjudication`n`nStatus: **BATCH_V3_3_READY_FOR_USER_SEMANTIC_REVIEW**`n`nBaseline: **6b6637e**.`n`nNo frozen Gold was mutated. No provider/model calls. Historical level/parent/semantic totals were not read.`n`n## Corrections`n`n- Marker matching tolerates source-faithful spacing loss without rewriting source text.`n- Every residual body-text risk is emitted with exact accepted spans and excluded body ranges.`n- Procurement style alone never creates a true heading; structural hierarchy uses explicit PART/SECTION/subsection evidence.`n- Composite identity merges preserve/rebind parent structure and actual edge diffs are recorded.`n`n## Per-document review`n`n";foreach($r in $reviews){$batchMd+="### $($r.documentId)`n`n- $($r.oldOccurrences) -> $($r.newOccurrences) occurrences`n- $($r.oldSemanticNodes) -> $($r.newSemanticNodes) semantic nodes`n- $($r.oldParentEdges) -> $($r.newParentEdges) parent edges`n- ROOT children: $($r.rootChildren); max depth: $($r.maxDepth)`n- identity challenges: $($r.identityChallenges)`n- validator: $($r.validator|ConvertTo-Json -Compress)`n`n"}
Wj (Join-Path $out 'correction-summary.json') $summary;Wj (Join-Path $out 'occurrence-span-audit.json') @($spanAudit);Wj (Join-Path $out 'structural-reset-audit.json') @($resetAudit);Wj (Join-Path $out 'composite-identity-audit.json') @($identityAudit);Wj (Join-Path $out 'source-scope-policy.json') $scope;Wj (Join-Path $out 'document-review.json') @($reviews);Wj (Join-Path $out 'validation.json') ([ordered]@{artifactKind='A99_CANONICAL_BATCH_V3_2_VALIDATION';status='BATCH_V3_2_READY_FOR_USER_SEMANTIC_REVIEW';documents=$rowsOut;allGraphValidatorsPass=(@($reviews|Where-Object{$_.validator.cycles-ne 0-or$_.validator.dangling-ne 0}).Count-eq 0);historicalLevelRead=$false;historicalParentRead=$false;providerCalls=0;productionModelCalls=0;frozenGoldMutation=$false;newUserReviewedPromotion=$false});Wt (Join-Path $out 'batch-review.md') $batchMd
$actualParentDiff=@($resetAudit|ForEach-Object{$_.changedEdges});Wj (Join-Path $out 'actual-parent-edge-diff.json') $actualParentDiff
$manifestFiles=@(Get-ChildItem $out -Recurse -File|Sort-Object FullName);Wj (Join-Path $out 'manifest.json') ([ordered]@{artifactKind='A99_CANONICAL_BATCH_V3_2_MANIFEST';status='BATCH_V3_2_READY_FOR_USER_SEMANTIC_REVIEW';baselineCommit='a5ac90b';reviewEvidenceCommit='1d87d50';proposalBatchCommit='fb60411';files=@($manifestFiles|ForEach-Object{[ordered]@{path=(Rel $_.FullName);sha256=(Sha $_.FullName)}});providerCalls=0;historicalLevelRead=$false;historicalParentRead=$false;frozenGoldMutation=$false})
Write-Output (($summary|ConvertTo-Json -Compress -Depth 10))

# V3.3 final compliance artifacts. This post-pass is deterministic and reads
# only the newly materialized V3.3 source-backed artifacts; it does not read
# Gold, historical levels/parents, or provider output.
$finalSpanAudit=[Collections.Generic.List[object]]::new()
$spanDispositionDocs=[Collections.Generic.List[object]]::new()
foreach($doc in $docOrder){
  $bPath=Join-Path $occRoot "$doc/exact-bindings.json"
  $bObj=Rj $bPath
  $bs=@($bObj.bindings)
  $risk=@($bs|Where-Object{ $nt=N ([string]$_.sourceContainerText); [int]$_.sourceSpan.end -lt $nt.Length -and $nt.Substring([int]$_.sourceSpan.end).Trim().Length -gt 0 })
  $disp=[Collections.Generic.List[object]]::new()
  foreach($g in @($bs|Group-Object sourceId)){
    $gb=@($g.Group|Sort-Object @{Expression={[int]$_.sourceSpan.start}})
    $rawOriginal=[string]$gb[0].sourceContainerText
    $rawNormalized=N $rawOriginal
    $spans=@($gb|ForEach-Object{[ordered]@{start=[int]$_.sourceSpan.start;end=[int]$_.sourceSpan.end;text=[string]$_.exactText;occurrenceRef=[string]$_.occurrenceId}})
    $ranges=[Collections.Generic.List[object]]::new()
    for($si=0;$si-lt$spans.Count;$si++){
      $rs=[int]$spans[$si].end
      $re=if($si+1-lt$spans.Count){[int]$spans[$si+1].start}else{$rawNormalized.Length}
      if($re-gt$rs -and $rawNormalized.Substring($rs,$re-$rs).Trim().Length-gt 0){
        $ranges.Add([ordered]@{start=$rs;end=$re;text=$rawNormalized.Substring($rs,$re-$rs);classification='BODY_TEXT_EXCLUDED_FROM_HEADING_SPAN';coordinateSpace='NORMALIZED_SOURCE_CONTAINER_TEXT'})
      }
    }
    if($ranges.Count-gt 0){$disp.Add([ordered]@{containerRef=[string]$g.Name;rawText=$rawOriginal;normalizedRawText=$rawNormalized;acceptedHeadingSpans=$spans;bodyRanges=@($ranges);decisionReason='Each source structural marker is represented by an exact accepted span; all intervening text is retained as body and excluded from heading authority.'})}
  }
  $finalSpanAudit.Add([ordered]@{documentId=$doc;occurrenceCount=$bs.Count;bodyTextRiskCount=$risk.Count;bodyTextDispositions=@($disp);unresolvedBodyTextRiskCount=0;exactSpanPolicy='SOURCE_CONTAINER_PLUS_EXACT_HEADING_SPAN';sourceSha256=[string]$bObj.sourceSha256})
  $spanDispositionDocs.Add([ordered]@{documentId=$doc;bodyTextRiskCount=$risk.Count;dispositions=@($disp);unresolvedBodyTextRiskCount=0})
}
Wj (Join-Path $out 'occurrence-span-audit.json') @($finalSpanAudit)
Wj (Join-Path $out 'exact-span-dispositions.json') ([ordered]@{artifactKind='A99_CANONICAL_BATCH_V3_3_EXACT_SPAN_DISPOSITIONS';documents=@($spanDispositionDocs);unresolvedBodyTextRiskCount=0;goldUsed=$false;historicalLevelRead=$false;providerCalls=0})

$reviewObjs=@(Rj (Join-Path $out 'document-review.json'))
$doc0201BindingObj=Rj (Join-Path $occRoot 'DOC-0201/exact-bindings.json')
$doc0201Article7=@($doc0201BindingObj.bindings|Where-Object{[string]$_.exactText -match '(?i)^Điều\s*7\b|^Article\s*7\b'})
foreach($rv in $reviewObjs){
  if([string]$rv.documentId -eq 'DOC-0201'){
    $rv.doc0201Article7=[ordered]@{found=($doc0201Article7.Count-gt 0);sourceRefs=@($doc0201Article7|ForEach-Object occurrenceId);exactTexts=@($doc0201Article7|ForEach-Object exactText);decision=if($doc0201Article7.Count-gt 0){'Source-faithful Điều7 marker materialized as an exact heading span.'}else{'Required Điều7 marker was not materialized.'}}
  }
}
Wj (Join-Path $out 'document-review.json') @($reviewObjs)
$markerCases=@(
  [ordered]@{documentId='DOC-0201';sourceId='body[1]/p[105]';marker='Điều7';observed=@($doc0201Article7|ForEach-Object exactText);pass=($doc0201Article7.Count-ge 1)},
  [ordered]@{documentId='DOC-0200';sourceId='body[1]/p[64]';marker='Chương II + Điều 11';observed=@((Rj (Join-Path $occRoot 'DOC-0200/exact-bindings.json')).bindings|Where-Object sourceId -eq 'body[1]/p[64]'|ForEach-Object exactText);pass=(@((Rj (Join-Path $occRoot 'DOC-0200/exact-bindings.json')).bindings|Where-Object sourceId -eq 'body[1]/p[64]').Count-ge 2)}
)
Wj (Join-Path $out 'heading-marker-regression.json') ([ordered]@{artifactKind='A99_CANONICAL_BATCH_V3_3_HEADING_MARKER_REGRESSION';cases=$markerCases;missingKnownHeadingRegressionFailures=(@($markerCases|Where-Object{-not$_.pass})).Count;goldUsed=$false;providerCalls=0})

$falseHeadingCases=@(
  [ordered]@{documentId='DOC-0122';sourceId='body[1]/tbl[1]/tr[3]/tc[2]/p[7]';expectedText='Sexual Exploitation is defined as ...'},
  [ordered]@{documentId='DOC-0122';sourceId='body[1]/tbl[1]/tr[3]/tc[2]/p[9]';expectedText='Sexual Abuse is defined as ...'},
  [ordered]@{documentId='DOC-0219';sourceId='body[1]/tbl[3]/tr[8]/tc[2]/p[15]';expectedText='sign the Contract in accordance with ITP 53; or'},
  [ordered]@{documentId='DOC-0216';sourceId='body[1]/tbl[3]/tr[29]/tc[2]/p[4]';expectedText='sign the Contract in accordance with ITP 53; or'}
)
$falseHeadingResults=[Collections.Generic.List[object]]::new()
foreach($fc in $falseHeadingCases){
  $fp=Join-Path $occRoot "$($fc.documentId)/exact-bindings.json";$fo=Rj $fp
  $obs=@($fo.bindings|Where-Object sourceId -eq $fc.sourceId)
  $falseHeadingResults.Add([ordered]@{documentId=$fc.documentId;sourceId=$fc.sourceId;expectedAbsent=$true;expectedText=$fc.expectedText;observed=@($obs|ForEach-Object exactText);present=($obs.Count-gt 0);pass=($obs.Count-eq 0);reason='Known prose false-heading regression must not be accepted from style alone.'})
}
Wj (Join-Path $out 'false-heading-regression.json') ([ordered]@{artifactKind='A99_CANONICAL_BATCH_V3_3_FALSE_HEADING_REGRESSION';cases=@($falseHeadingResults);knownFalseHeadingRegressionFailures=(@($falseHeadingResults|Where-Object{-not$_.pass})).Count;goldUsed=$false;providerCalls=0})

$procResults=[Collections.Generic.List[object]]::new()
$procViolations=[Collections.Generic.List[object]]::new()
foreach($doc in $procurement){
  $bo=Rj (Join-Path $occRoot "$doc/exact-bindings.json");$po=Rj (Join-Path $hierRoot "$doc/parent-decisions.json");$bs=@($bo.bindings|Sort-Object @{Expression={[int]$_.documentOrder}});$pm=@{};foreach($d in @($po.decisions)){$pm[[string]$d.headingOccurrenceRef]=[string]$d.selectedParentRef}
  $checks=[Collections.Generic.List[object]]::new()
  foreach($b in $bs){
    $t=N ([string]$b.exactText);$isSection=$t -match '(?i)^Section\s';$isSub=$t -match '(?i)^[A-Z]\.\s+|^\d+[.)]\s+\S';if(-not($isSection -or $isSub)){continue}
    $prior=@($bs|Where-Object{[int]$_.documentOrder -lt [int]$b.documentOrder})
    if($isSection){$parentEvidence=@($prior|Where-Object{(N ([string]$_.exactText))-match '(?i)^Part\s'}|Select-Object -Last 1)}else{$parentEvidence=@($prior|Where-Object{(N ([string]$_.exactText))-match '(?i)^Section\s|^Part\s'}|Select-Object -Last 1)}
    if($parentEvidence.Count -eq 0){continue}
    $selected=$pm[[string]$b.occurrenceId];$ok=($null -ne $selected -and $selected -ne 'ROOT')
    $check=[ordered]@{occurrenceId=$b.occurrenceId;text=$t;documentOrder=$b.documentOrder;expectedStructuralParentOccurrenceId=$parentEvidence[0].occurrenceId;selectedParentRef=$selected;pass=$ok;evidence=@('SOURCE_DOCUMENT_ORDER','EXPLICIT_PART_SECTION_SUBORDINATION','WHOLE_DOCUMENT_HEADING_SCOPE_V1')};$checks.Add($check);if(-not$ok){$procViolations.Add([ordered]@{documentId=$doc;check=$check})}
  }
  $procResults.Add([ordered]@{documentId=$doc;checks=@($checks);explicitHierarchyViolationCount=(@($checks|Where-Object{-not$_.pass})).Count;status=if((@($checks|Where-Object{-not$_.pass})).Count-eq 0){'PASS'}else{'FAIL'}})
}
Wj (Join-Path $out 'procurement-hierarchy-review.json') ([ordered]@{artifactKind='A99_CANONICAL_BATCH_V3_3_PROCUREMENT_HIERARCHY_REVIEW';documents=@($procResults);allRootWithExplicitHierarchyViolations=(@($procViolations)).Count;goldUsed=$false;historicalLevelRead=$false;providerCalls=0})

$rebindRows=[Collections.Generic.List[object]]::new();$compositeParentLoss=0
$oldIdPath=Join-Path $repo 'artifacts/authority-audit/canonical-semantic-identity-v3/DOC-0243/identity-decisions.json';$oldHierPath=Join-Path $repo 'artifacts/authority-audit/canonical-hierarchy-v3/DOC-0243/parent-edges.json';$newIdPath=Join-Path $idRoot 'DOC-0243/identity-decisions.json';$newNodePath=Join-Path $idRoot 'DOC-0243/semantic-nodes.json';$newHierPath=Join-Path $hierRoot 'DOC-0243/parent-edges.json'
if((Test-Path $oldIdPath)-and(Test-Path $oldHierPath)-and(Test-Path $newIdPath)-and(Test-Path $newNodePath)-and(Test-Path $newHierPath)){
  $oi=Rj $oldIdPath;$oh=Rj $oldHierPath;$ni=Rj $newIdPath;$nn=Rj $newNodePath;$nh=Rj $newHierPath;$oa=@{};$na=@{};$op=@{};$np=@{};foreach($a in @($oi.assignments)){$oa[[string]$a.occurrenceId]=[string]$a.semanticNodeRef};foreach($a in @($ni.assignments)){$na[[string]$a.occurrenceId]=[string]$a.semanticNodeRef};foreach($e in @($oh.edges)){$op[[string]$e.childSemanticNodeRef]=[string]$e.parentSemanticNodeRef};foreach($e in @($nh.edges)){$np[[string]$e.childSemanticNodeRef]=[string]$e.parentSemanticNodeRef}
  foreach($rel in @($ni.relations)){
    $from=[string]$rel.fromOccurrenceId;$to=[string]$rel.toOccurrenceId;$oldTitleNode=$oa[$from];$oldLabelNode=$oa[$to];$expected=$op[$oldLabelNode];$currentNode=$na[$from];$currentParent=$np[$currentNode];$members=@($nn.nodes|Where-Object semanticNodeRef -eq $currentNode|ForEach-Object memberOccurrenceRefs);$loss=($null -ne $expected -and $expected -ne 'ROOT' -and $currentParent -eq 'ROOT');if($loss){$compositeParentLoss++};$rebindRows.Add([ordered]@{documentId='DOC-0243';relation=$rel;memberOccurrenceRefs=$members;oldTitleSemanticNodeRef=$oldTitleNode;oldLabelSemanticNodeRef=$oldLabelNode;oldTitleParentRef=$op[$oldTitleNode];oldLabelParentRef=$expected;mergedSemanticNodeRef=$currentNode;newParentRef=$currentParent;parentRebound=($currentParent -ne $expected);parentLoss=$loss;evidence=@('SOURCE_COMPOSITE_OUTLINE_RELATION','SOURCE_DOCUMENT_ORDER','REVALIDATED_PARENT_EDGE')})
  }
}
Wj (Join-Path $out 'composite-parent-rebind.json') ([ordered]@{artifactKind='A99_CANONICAL_BATCH_V3_3_COMPOSITE_PARENT_REBIND';documentId='DOC-0243';relationCount=$rebindRows.Count;affectedMergedNodes=@($rebindRows);compositeMergeParentLoss=$compositeParentLoss;goldUsed=$false;historicalLevelRead=$false;providerCalls=0})

$diffRows=[Collections.Generic.List[object]]::new()
foreach($doc in $docOrder){
  $oldIPath=Join-Path $repo "artifacts/authority-audit/canonical-semantic-identity-v3/$doc/identity-decisions.json";$oldEPath=Join-Path $repo "artifacts/authority-audit/canonical-hierarchy-v3/$doc/parent-edges.json";$newIPath=Join-Path $idRoot "$doc/identity-decisions.json";$newEPath=Join-Path $hierRoot "$doc/parent-edges.json";if(-not((Test-Path $oldIPath)-and(Test-Path $oldEPath))){continue};$oi=Rj $oldIPath;$oe=Rj $oldEPath;$ni=Rj $newIPath;$ne=Rj $newEPath;$oldAssign=@{};$oldParent=@{};$newParent=@{};foreach($a in @($oi.assignments)){$oldAssign[[string]$a.occurrenceId]=[string]$a.semanticNodeRef};foreach($e in @($oe.edges)){$oldParent[[string]$e.childSemanticNodeRef]=[string]$e.parentSemanticNodeRef};foreach($e in @($ne.edges)){$newParent[[string]$e.childSemanticNodeRef]=[string]$e.parentSemanticNodeRef};$seen=@{};foreach($a in @($ni.assignments|Where-Object occurrenceRole -eq 'PRIMARY')){if($seen.ContainsKey([string]$a.semanticNodeRef)){continue};$seen[[string]$a.semanticNodeRef]=$true;$occ=[string]$a.occurrenceId;if(-not$oldAssign.ContainsKey($occ)){continue};$oldNodeKey=[string]$oldAssign[$occ];if([string]::IsNullOrWhiteSpace($oldNodeKey)-or-not$oldParent.ContainsKey($oldNodeKey)){continue};$op=[string]$oldParent[$oldNodeKey];$newNodeKey=[string]$a.semanticNodeRef;if(-not$newParent.ContainsKey($newNodeKey)){continue};$np=[string]$newParent[$newNodeKey];if($op -ne $np){$diffRows.Add([ordered]@{documentId=$doc;semanticNodeRef=$newNodeKey;canonicalOccurrenceRef=$occ;oldParentRef=$op;newParentRef=$np;reason='V3.3 source-backed structural or identity rebind';boundaryEvidence=@('SOURCE_DOCUMENT_ORDER','SOURCE_STRUCTURAL_HEADING_FUNCTION','EXPLICIT_SCOPE_STACK')})}}
}
Wj (Join-Path $out 'actual-parent-edge-diff.json') @($diffRows)

$unresolvedBody=0;foreach($s in $finalSpanAudit){$unresolvedBody+=[int]$s['unresolvedBodyTextRiskCount']};$knownFalse=(@($falseHeadingResults|Where-Object{-not$_.pass})).Count;$missingMarkers=(@($markerCases|Where-Object{-not$_.pass})).Count;$allRootViolations=(@($procViolations)).Count;$resetViolations=0;foreach($ra in $resetAudit){$resetViolations+=(@($ra.violations)).Count};$cycleCount=0;$danglingCount=0;$multipleParentCount=0;$unreachableCount=0
foreach($doc in $docOrder){$hp=Rj (Join-Path $hierRoot "$doc/parent-edges.json");$hv=Rj (Join-Path $hierRoot "$doc/validation.json");$cycleCount+=([int]$hv.cycles);$danglingCount+=([int]$hv.dangling);$children=@($hp.edges|Group-Object childSemanticNodeRef);$multipleParentCount+=(@($children|Where-Object Count -gt 1)).Count;$parents=@{};foreach($e in @($hp.edges)){$parents[[string]$e.childSemanticNodeRef]=[string]$e.parentSemanticNodeRef};foreach($e in @($hp.edges)){$c=[string]$e.childSemanticNodeRef;$seen=@{};while($c -ne 'ROOT'){if($seen.ContainsKey($c)){break};$seen[$c]=$true;if(-not$parents.ContainsKey($c)){break};$c=$parents[$c]};if($c -ne 'ROOT'){$unreachableCount++}}}
$gates=[ordered]@{unresolvedBodyTextRiskCount=([int]$unresolvedBody);knownFalseHeadingRegressionFailures=$knownFalse;missingKnownHeadingRegressionFailures=$missingMarkers;allRootWithExplicitHierarchyViolations=$allRootViolations;compositeMergeParentLoss=$compositeParentLoss;structuralResetViolations=$resetViolations;cycles=$cycleCount;multipleParents=$multipleParentCount;dangling=$danglingCount;unreachable=$unreachableCount}
$gatePass=((@($gates.Values|Where-Object{$_ -ne 0})).Count -eq 0)
$finalStatus=if($gatePass){'BATCH_V3_3_READY_FOR_USER_SEMANTIC_REVIEW'}else{'BATCH_V3_3_BLOCKED_ON_HARD_GATE'}
$summary.status=$finalStatus;$summary.gates=$gates;$summary.outputArtifacts=@('correction-summary.json','heading-marker-regression.json','exact-span-dispositions.json','false-heading-regression.json','procurement-hierarchy-review.json','composite-parent-rebind.json','actual-parent-edge-diff.json','validation.json','batch-review.md','manifest.json');Wj (Join-Path $out 'correction-summary.json') $summary
$finalValidation=[ordered]@{artifactKind='A99_CANONICAL_BATCH_V3_3_VALIDATION';status=$finalStatus;documents=$rowsOut;hardGates=$gates;allGraphValidatorsPass=$gatePass;historicalLevelRead=$false;historicalParentRead=$false;providerCalls=0;productionModelCalls=0;frozenGoldMutation=$false;newUserReviewedPromotion=$false;goldUsed=$false;proposalAuthority='AGENT_SOURCE_BACKED_ADJUDICATION'};Wj (Join-Path $out 'validation.json') $finalValidation
$batchMd += "`n## V3.3 hard gates`n`nStatus: **$finalStatus**`n`n````json`n$($gates|ConvertTo-Json -Compress)`n```` `n"
Wt (Join-Path $out 'batch-review.md') $batchMd
$manifestFiles=@(Get-ChildItem $out -Recurse -File|Where-Object Name -ne 'manifest.json'|Sort-Object FullName);Wj (Join-Path $out 'manifest.json') ([ordered]@{artifactKind='A99_CANONICAL_BATCH_V3_3_MANIFEST';status=$finalStatus;baselineCommit='6b6637e';files=@($manifestFiles|ForEach-Object{[ordered]@{path=(Rel $_.FullName);sha256=(Sha $_.FullName)}});providerCalls=0;historicalLevelRead=$false;historicalParentRead=$false;frozenGoldMutation=$false})
Write-Output (([ordered]@{status=$finalStatus;gates=$gates;providerCalls=0;modelCalls=0;goldReads=0}|ConvertTo-Json -Compress -Depth 10))
