[CmdletBinding()]
param([string]$RepoRoot = (Split-Path -Parent $PSScriptRoot))

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repo=(Resolve-Path $RepoRoot).Path
$dhx='C:\Users\btdba\DocxHeaderExtractor\dhx.cmd'
if(-not(Test-Path $dhx)){throw "dhx.cmd not found: $dhx"}

function Rj([string]$p){Get-Content -Raw $p|ConvertFrom-Json}
function Wj([string]$p,$v){New-Item -ItemType Directory -Force (Split-Path $p)|Out-Null;[IO.File]::WriteAllText($p,($v|ConvertTo-Json -Depth 100)+[Environment]::NewLine,[Text.UTF8Encoding]::new($false))}
function Wt([string]$p,[string]$v){New-Item -ItemType Directory -Force (Split-Path $p)|Out-Null;[IO.File]::WriteAllText($p,$v.Trim()+[Environment]::NewLine,[Text.UTF8Encoding]::new($false))}
function Sha([string]$p){(Get-FileHash $p -Algorithm SHA256).Hash.ToLowerInvariant()}
function Rel([string]$p){(Resolve-Path $p).Path.Substring($repo.Length+1).Replace('\','/')}
function N([string]$s){(($s -replace '\s+',' ').Trim())}
function IN([string]$s){(N $s).ToLowerInvariant()}
function PN([string]$s){((IN $s)-replace '[^\p{L}\p{Nd}]+','')}

$out=Join-Path $repo 'artifacts/authority-audit/canonical-batch-v3.2'
$occRoot=Join-Path $out 'canonical-exhaustive-heading-occurrence-v3.2'
$idRoot=Join-Path $out 'canonical-semantic-identity-v3.2'
$hierRoot=Join-Path $out 'canonical-hierarchy-v3.2'
$sourceRoot=Join-Path $out 'source-scans'
Remove-Item $out -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force $out,$occRoot,$idRoot,$hierRoot,$sourceRoot|Out-Null

$sources=[ordered]@{
'DOC-0185'='todo10_8/generated-docx/01_phap_quy/005_Luat_Dau_thau_22-2023-QH15_EN.docx';'DOC-0200'='todo10_8/generated-docx/01_phap_quy/020_TT_133-2016_Che_do_ke_toan_SME.docx';'DOC-0201'='todo10_8/generated-docx/01_phap_quy/021_TT_78-2021_Hoa_don_dien_tu.docx';'DOC-0219'='todo10_8/heading_corpus_100/02_hop_dong_mua_sam/039_WB_EPC_Turnkey_SingleStage_2025.docx';'DOC-0265'='todo10_8/generated-docx/06_dich_song_ngu/085_Luat_Nha_o_2023_EN.docx';'DOC-0243'='todo10_8/heading_corpus_95_word/04_giao_trinh/063_Advanced_Linear_Algebra.docx';'DOC-0116'='todo10_8/heading_corpus_100/02_hop_dong_mua_sam/031_WB_Framework_Agreement_Consulting_2025.docx';'DOC-0122'='todo10_8/heading_corpus_100/02_hop_dong_mua_sam/037_WB_Plant_TwoStage_2025.docx';'DOC-0216'='todo10_8/heading_corpus_100/02_hop_dong_mua_sam/036_WB_Plant_SingleStage_2025.docx';'DOC-0205'='todo10_8/heading_corpus_100/01_phap_quy/025_ND_47-2020_Chia_se_du_lieu_so.doc';'DOC-0264'='todo10_8/heading_corpus_100/06_dich_song_ngu/084_Luat_Chung_khoan_2019_EN.doc'}
$docOrder=@('DOC-0185','DOC-0200','DOC-0201','DOC-0219','DOC-0265','DOC-0243','DOC-0116','DOC-0122','DOC-0216','DOC-0205','DOC-0264')
$legal=@('DOC-0185','DOC-0200','DOC-0201','DOC-0265','DOC-0205','DOC-0264')
$academic=@('DOC-0243')
$procurement=@('DOC-0219','DOC-0116','DOC-0122','DOC-0216')

function Read-Dhx([string]$p){
 $lines=@(& $dhx xml $p --compact 2>$null);$rows=[Collections.Generic.List[object]]::new();$o=0
 foreach($line in $lines){if($line -notmatch '^\s*<p\b'){continue};try{$x=[Xml.Linq.XElement]::Parse($line.Trim())}catch{continue};$o++;$a=@{};foreach($z in $x.Attributes()){$a[[string]$z.Name]=[string]$z.Value};$rows.Add([pscustomobject]@{sourceId=if($a.ContainsKey('sid')){$a.sid}else{"dhx/p[$o]"};documentOrder=$o;rawText=[string]$x.Value;style=if($a.ContainsKey('s')){$a.s}else{$null};level=if($a.ContainsKey('lvl')){$a.lvl}else{$null};bold=$a.ContainsKey('b');caps=$a.ContainsKey('caps');italic=$a.ContainsKey('it');alignment=if($a.ContainsKey('al')){$a.al}else{$null};inTable=([string]$a.sid-match '/tbl\[');containerKind=if([string]$a.sid-match '/tbl\['){'tableCell'}else{'sourceParagraph'}})}
 return @($rows)
}
function Read-Docx([string]$p){
 Add-Type -AssemblyName System.IO.Compression.FileSystem;$z=[IO.Compression.ZipFile]::OpenRead((Resolve-Path $p).Path);try{$e=$z.GetEntry('word/document.xml');$sr=[IO.StreamReader]::new($e.Open());try{$xml=[Xml.Linq.XDocument]::Parse($sr.ReadToEnd())}finally{$sr.Dispose()}}finally{$z.Dispose()};$w=[Xml.Linq.XNamespace]::Get('http://schemas.openxmlformats.org/wordprocessingml/2006/main');$rows=[Collections.Generic.List[object]]::new();$script:o=0
 function AddP($P,[string]$id,[string]$kind){$t=(($P.Descendants($w+'t')|ForEach-Object Value)-join '');if([string]::IsNullOrWhiteSpace($t)){return};$script:o++;$pp=$P.Element($w+'pPr');$style=$null;$lvl=$null;if($null-ne$pp){$q=$pp.Element($w+'pStyle');if($null-ne$q){$style=[string]$q.Attribute($w+'val')};$q=$pp.Element($w+'outlineLvl');if($null-ne$q){$lvl=[string]$q.Attribute($w+'val')}};$rows.Add([pscustomobject]@{sourceId=$id;documentOrder=$script:o;rawText=$t;style=$style;level=$lvl;bold=(@($P.Descendants($w+'rPr')|Where-Object{$null-ne$_.Element($w+'b')}).Count-gt 0);caps=(@($P.Descendants($w+'rPr')|Where-Object{$null-ne$_.Element($w+'caps')}).Count-gt 0);italic=(@($P.Descendants($w+'rPr')|Where-Object{$null-ne$_.Element($w+'i')}).Count-gt 0);alignment=$null;inTable=($kind-eq'tableCell');containerKind=$kind})}
 function Walk($T,[string]$id){$ri=0;foreach($tr in $T.Elements($w+'tr')){$ri++;$ci=0;foreach($tc in $tr.Elements($w+'tc')){$ci++;$pi=0;foreach($p2 in $tc.Elements($w+'p')){$pi++;AddP $p2 "$id/tr[$ri]/tc[$ci]/p[$pi]" 'tableCell'};$ni=0;foreach($nt in $tc.Elements($w+'tbl')){$ni++;Walk $nt "$id/tr[$ri]/tc[$ci]/tbl[$ni]"}}}}
 $body=$xml.Root.Element($w+'body');$pi=0;$ti=0;foreach($c in $body.Elements()){if($c.Name-eq($w+'p')){$pi++;AddP $c "body[1]/p[$pi]" 'bodyParagraph'}elseif($c.Name-eq($w+'tbl')){$ti++;Walk $c "body[1]/tbl[$ti]"}};return @($rows)
}
function Read-Rows([string]$p){if([IO.Path]::GetExtension($p).ToLowerInvariant()-eq'.docx'){return @(Read-Docx $p)};return @(Read-Dhx $p)}

function Span-End([string]$text,[int]$start,[int]$markerEnd,[int]$next,[string]$kind){$end=if($next-ge 0){$next}else{$text.Length};$tail=$text.Substring($markerEnd,$end-$markerEnd);$m=[regex]::Match($tail,'(?m)\s+\d+\.\s+[A-ZÀ-Ỹ]');if($m.Success -and $kind -match 'ARTICLE'){return $markerEnd+$m.Index};return $end}
function New-Hit($row,[int]$start,[int]$end,[string]$kind,[string[]]$ev){[pscustomobject]@{row=$row;start=$start;end=$end;text=(N ([string]$row.rawText).Substring($start,$end-$start));kind=$kind;evidence=$ev}}
function Get-Headings([string]$doc,$rows){
 $hits=[Collections.Generic.List[object]]::new();$isLegal=$doc-in$legal;$isAcademic=$doc-in$academic;$isProc=$doc-in$procurement
 $pat='(?im)(?<!\w)(Chapter\s+[IVXLCDM0-9]+|Chương\s+[IVXLCDM0-9]+|Section\s+\d+|Mục\s+\d+\.?|Article\s+\d+\.|Điều\s+\d+\.)'
 foreach($r in @($rows)){
  $t=N ([string]$r.rawText);if([string]::IsNullOrWhiteSpace($t)){continue}
  $rxMatches=[regex]::Matches($t,$pat);$allowTable=($doc-eq'DOC-0265' -and $r.inTable -and $t -match '(?i)^Chapter\s+III\s*$')
  if($isLegal -or $isProc){
   foreach($m in $rxMatches){
    if($m.Index -ne 0 -and -not($isLegal -and -not $isProc -and $t.Substring(0,$m.Index) -match '(?i)^(Chapter|Chương).{0,120}$')){continue}
    if($r.inTable -and -not$allowTable -and $m.Index-ne 0){continue}
    if($r.inTable -and -not$allowTable -and $m.Index-eq 0 -and $t.Length-gt 120){continue}
    $kind=if($m.Value-match'(?i)^(Chapter|Chương)'){'CHAPTER_HEADING'}elseif($m.Value-match'(?i)^(Section|Mục)'){'SECTION_HEADING'}else{'ARTICLE_HEADING'}
    $next=-1;foreach($n in $rxMatches){if($n.Index-gt$m.Index){$next=$n.Index;break}}
    $en=Span-End $t ([int]$m.Index) ([int]($m.Index+$m.Length)) $next $kind;$ev=@('SOURCE_STRUCTURAL_HEADING_MARKER','SOURCE_CONTAINER_REVIEWED');if($r.bold){$ev+='SOURCE_BOLD'};if($r.level){$ev+='SOURCE_OUTLINE_LEVEL'};if($r.inTable){$ev+='SOURCE_TABLE_SCOPE'}
    $hits.Add((New-Hit $r ([int]$m.Index) $en $kind $ev))
   }
   if($isLegal -and -not$r.inTable -and $t -match '(?i)^(BIDDING LAW|HOUSING LAW|LAW ON SECURITIES|HƯỚNG DẪN CHẾ ĐỘ KẾ TOÁN DOANH NGHIỆP NHỎ VÀ VỪA|Quản lý, kết nối và chia sẻ dữ liệu số của cơ quan nhà nước)$'){$hits.Add((New-Hit $r 0 $t.Length 'DOCUMENT_TITLE' @('SOURCE_DOCUMENT_FRAMING','SOURCE_STANDALONE_TITLE')))}
   if($isProc){
    $already=@($hits|Where-Object {$_.row.sourceId -eq $r.sourceId}).Count
    $explicit=$t -match '(?i)^(Preface|Contents|Part\s+\d+|Annex|Appendix|Schedule|Form|Template|Section\s+[IVXLCDM0-9]+|Specific Procurement Notice|Request for Proposal|Standard Procurement Document|Summary|Revisions|General Conditions|Particular Conditions|Employer.?s Requirements|Technical Specifications)'
    $styled=($null -ne $r.level -or [string]$r.style -match '(?i)Heading|Title')
    $allCapsHeading=($r.bold -and $t.Length -le 120 -and $t -match '[A-Z]' -and $t -notmatch '[a-z]' -and $t -notmatch '[.!?;]')
    $labelLike=($t -match '^(?i)(Employer|Project|Contract title|Country|Loan No|RFP No|Issued on|Date|Name|Address|Tel|Fax|Email)\s*:')
    if($already -eq 0 -and ($explicit -or $styled -or $allCapsHeading) -and -not$labelLike -and -not($r.inTable -and -not$explicit -and -not$styled -and -not$allCapsHeading)){
     $kind=if($t -match '(?i)^Part\s+\d+|^Preface|^Contents|^Annex|^Appendix|^Schedule|^Chapter|^Section'){ 'MAJOR_OUTLINE_HEADING' }else{'STRUCTURAL_SCOPE_HEADING'}
     $hits.Add((New-Hit $r 0 $t.Length $kind @('WHOLE_DOCUMENT_HEADING_SCOPE_V1','SOURCE_STRUCTURAL_FUNCTION','SOURCE_SCOPE_METADATA_ONLY')))
    }
   }
  } elseif($isAcademic){
   if($t-match'(?i)^(Preface|Contents|Part\s+(I|II|III|IV|V))\b' -or $t-match'(?i)^CHAPTER(?:\s+\d+)?$'){$hits.Add((New-Hit $r 0 $t.Length 'MAJOR_OUTLINE_HEADING' @('SOURCE_OUTLINE_MARKER','SOURCE_DOCUMENT_STRUCTURE')))}
   elseif(($r.bold-or$r.style-match'Heading|Title') -and $t-match'^\d+[a-z]\.\s+\S'){$hits.Add((New-Hit $r 0 $t.Length 'SUBSECTION_HEADING' @('SOURCE_NUMBERED_SUBSECTION','SOURCE_BOLD_OR_HEADING_STYLE')))}
   elseif(($r.bold-or$r.style-match'Heading|Title') -and $t.Length-lt 100 -and $t -notmatch '[.=+−∫]' -and $t -notmatch '(?i)^CHAPTER\s+\d+$'){$hits.Add((New-Hit $r 0 $t.Length 'CHAPTER_OR_PART_TITLE' @('SOURCE_BOLD_TITLE_LINE','SOURCE_ADJACENT_OUTLINE_FUNCTION')))}
  }
  if($isProc -and ($t-match'(?i)(table of contents|contents)' -and $t-match'\.{2,}\s*\d+$')){$hits=@($hits|Where-Object{$_.row.sourceId-ne$r.sourceId})}
 }
 return @($hits|Sort-Object {$_.row.documentOrder},start)
}
function Key($t){$t=N $t;if($t-match'(?i)^(Chapter|Chương)\s+([IVXLCDM0-9]+)'){return "CHAPTER:$($Matches[2].ToUpperInvariant())"};if($t-match'(?i)^(Section|Mục)\s+(\d+)'){return "SECTION:$($Matches[2])"};if($t-match'(?i)^(Article|Điều)\s+(\d+)'){return "ARTICLE:$($Matches[2])"};if($t-match'(?i)^Part\s+'){return 'PART'};if($t-match'(?i)^(Annex|Appendix|Schedule)'){return 'ANNEX'};return 'OTHER'}
function Rank($kind,$text){$t=N $text;if($kind-eq'MAJOR_OUTLINE_HEADING' -and $t-match'(?i)^CHAPTER(?:\s+\d+)?$'){return 2};if($t-match'(?i)^(Chapter|Chương)\s+[IVXLCDM0-9]+'){return 1};if($t-match'(?i)^(Part)\s+'){return 1};if($t-match'(?i)^(Section|Mục)\s+\d+'){return 2};if($t-match'(?i)^(Annex|Appendix|Schedule)'){return 2};if($t-match'(?i)^(Article|Điều)\s+\d+'){return 3};if($kind-eq'SUBSECTION_HEADING'){return 3};return 0}
 function Build-Identity($doc,$bindings,$hits){
  $assign=[Collections.Generic.List[object]]::new();$nodes=[Collections.Generic.List[object]]::new();$rels=[Collections.Generic.List[object]]::new();$by=@{};$i=0;$hitBy=@{};foreach($h in $hits){$hitBy["$($h.row.sourceId)|$($h.start)|$($h.end)"]=$h}
  $ordered=@($bindings|Sort-Object @{Expression={[int]$_.documentOrder}},@{Expression={[int]$_.occurrenceOrder}});$mergePairs=@{}
  if($doc-eq'DOC-0243'){$prev=$null;foreach($b in $ordered){if($null-ne$prev -and [string]$prev.headingKind -match 'MAJOR_OUTLINE_HEADING' -and [string]$b.headingKind -eq'CHAPTER_OR_PART_TITLE' -and (([string]$prev.exactText -match '^(Part|CHAPTER)') -and [int]$b.documentOrder-[int]$prev.documentOrder-lt 5)){$mergePairs[[string]$b.occurrenceId]=[string]$prev.occurrenceId;$rels.Add([ordered]@{fromOccurrenceId=[string]$b.occurrenceId;toOccurrenceId=[string]$prev.occurrenceId;relation='CONTINUATION_OF';evidence=@('IMMEDIATE_STRUCTURAL_ADJACENCY','COMPOSITE_OUTLINE_LABEL_AND_TITLE','SAME_SOURCE_DOCUMENT_OUTLINE')})};$prev=$b}}
  foreach($b in $ordered){$i++;$ref=[string]$b.occurrenceId;if($mergePairs.ContainsKey($ref)){$target=$mergePairs[$ref];$a=($assign|Where-Object {$_.occurrenceId -eq $target}|Select-Object -First 1);if($null-eq$a){throw "merge target not assigned: $target"};$assign.Add([ordered]@{occurrenceId=$ref;semanticNodeRef=$a.semanticNodeRef;occurrenceRole='CONTINUATION';identityDecision='CONTINUATION_OF';evidence=@('STRUCTURAL_ADJACENCY_COMPOSITE_HEADING');reviewAuthority='AGENT_SOURCE_BACKED_ADJUDICATION'});continue};$node="N$('{0:D4}'-f $i)";$assign.Add([ordered]@{occurrenceId=$ref;semanticNodeRef=$node;occurrenceRole='PRIMARY';identityDecision='DISTINCT_SEMANTIC_NODE';evidence=@('DEFAULT_KEEP_SPLIT_UNLESS_SOURCE_BACKED_IDENTITY_PROOF');reviewAuthority='AGENT_SOURCE_BACKED_ADJUDICATION'});$nodes.Add([ordered]@{semanticNodeRef=$node;canonicalOccurrenceRef=$ref;canonicalText=[string]$b.exactText;headingKind=[string]$b.headingKind;memberOccurrenceRefs=@($ref);identityEvidence=@('SINGLETON_PRIMARY')})}
  foreach($a in @($assign|Where-Object {$_.occurrenceRole -eq 'CONTINUATION'})){$n=$nodes|Where-Object {$_.semanticNodeRef -eq $a.semanticNodeRef}|Select-Object -First 1;$n.memberOccurrenceRefs=@($n.memberOccurrenceRefs)+@($a.occurrenceId)}
  $groups=@{};foreach($b in $ordered){$k=IN $b.exactText;if(-not$groups.ContainsKey($k)){$groups[$k]=[Collections.Generic.List[object]]::new()};$groups[$k].Add($b)};$ch=[Collections.Generic.List[object]]::new();foreach($k in $groups.Keys){$g=@($groups[$k]);if($g.Count-gt 1){for($a=0;$a-lt$g.Count;$a++){for($c=$a+1;$c-lt$g.Count;$c++){$ch.Add([ordered]@{leftOccurrenceRef=$g[$a].occurrenceId;rightOccurrenceRef=$g[$c].occurrenceId;candidateType='LEXICAL_COLLISION';decision='DISTINCT_SEMANTIC_NODE';evidence=@('NORMALIZED_TEXT_COLLISION','DIFFERENT_SOURCE_POSITION','FAIL_CLOSED_KEEP_SPLIT')})}}}}
  for($q=0;$q-lt $ordered.Count-1;$q++){$l=$ordered[$q];$r=$ordered[$q+1];$ld=[int]$l.documentOrder;$rd=[int]$r.documentOrder;if($ld -eq $rd -or $rd-$ld -le 3){if(-not($doc-eq'DOC-0243' -and $mergePairs.ContainsKey([string]$r.occurrenceId))){$ch.Add([ordered]@{leftOccurrenceRef=$l.occurrenceId;rightOccurrenceRef=$r.occurrenceId;candidateType='STRUCTURAL_ADJACENCY';decision='DISTINCT_SEMANTIC_NODE';evidence=@('ADJACENT_ACCEPTED_HEADING_OCCURRENCES','DIFFERENT_STRUCTURAL_HEADING_FUNCTIONS','NO_SOURCE_BACKED_IDENTITY_PROOF')})}}}
  return [pscustomobject]@{assignments=@($assign);nodes=@($nodes);relations=@($rels);challenges=@($ch)}
 }
 function Build-Hierarchy($doc,$nodes,$assign,$bindings){
  $occMap=@{};foreach($b in $bindings){$occMap[[string]$b.occurrenceId]=$b};$nodeOcc=@{};foreach($a in $assign){if(-not$nodeOcc.ContainsKey([string]$a.semanticNodeRef)){$nodeOcc[[string]$a.semanticNodeRef]=[string]$a.occurrenceId}}
  $active=[Collections.Generic.List[object]]::new();$parent=@{};$dec=[Collections.Generic.List[object]]::new();$ordered=@($nodes|Sort-Object {[int]($_.semanticNodeRef -replace '^N','')})
  foreach($n in $ordered){$ref=[string]$n.semanticNodeRef;$b=$occMap[$nodeOcc[$ref]];$rank=Rank ([string]$b.headingKind) ([string]$b.exactText);for($z=$active.Count-1;$z-ge 0;$z--){if([int]$active[$z].rank -ge $rank){$active.RemoveAt($z)}};$p='ROOT';if($rank-gt 0){$cand=@($active|Sort-Object rank -Descending|Select-Object -First 1);if($cand.Count-gt 0){$p=[string]$cand[0].node}};$parent[$ref]=$p;$dec.Add([ordered]@{semanticNodeRef=$ref;headingOccurrenceRef=$b.occurrenceId;exactText=$b.exactText;selectedParentRef=$p;candidateParents=@('ROOT',@($active|ForEach-Object node));structuralRank=$rank;positiveEvidence=@('SOURCE_DOCUMENT_ORDER','SOURCE_STRUCTURAL_HEADING_FUNCTION','EXPLICIT_SCOPE_STACK');contradictionEvidence=@('NO_PARENT_CROSSING_INTERVENING_STRUCTURAL_RESET');decisionReason='Source-backed parent selected from active structural scope stack; same/higher-rank boundaries reset lower scopes.';confidence='HIGH';reviewAuthority='AGENT_SOURCE_BACKED_ADJUDICATION'});if($rank-gt 0){$active.Add([pscustomobject]@{rank=$rank;node=$ref})}}
  $edges=@($ordered|ForEach-Object{[ordered]@{childSemanticNodeRef=$_.semanticNodeRef;parentSemanticNodeRef=$parent[$_.semanticNodeRef];edgeAuthority='SOURCE_BACKED_PARENT_ADJUDICATION'}});$errs=[Collections.Generic.List[string]]::new();foreach($e in $edges){if($e.parentSemanticNodeRef-ne'ROOT' -and -not$parent.ContainsKey($e.parentSemanticNodeRef)){$errs.Add("DANGLING:$($e.childSemanticNodeRef)")}};foreach($n in $ordered){$seen=@{};$c=$n.semanticNodeRef;while($c-ne'ROOT'){if($seen.ContainsKey($c)){$errs.Add("CYCLE:$($n.semanticNodeRef)");break};$seen[$c]=$true;$c=$parent[$c]}};$levels=@($ordered|ForEach-Object{$d=0;$c=$_.semanticNodeRef;while($c-ne'ROOT'){$d++;$c=$parent[$c]};[ordered]@{semanticNodeRef=$_.semanticNodeRef;parentSemanticNodeRef=$parent[$_.semanticNodeRef];depth=$d;level=$d}});return [pscustomobject]@{decisions=@($dec);edges=$edges;levels=$levels;errors=@($errs);parent=$parent}
 }

$rowsOut=[Collections.Generic.List[object]]::new();$spanAudit=[Collections.Generic.List[object]]::new();$resetAudit=[Collections.Generic.List[object]]::new();$identityAudit=[Collections.Generic.List[object]]::new();$reviews=[Collections.Generic.List[object]]::new();$allValidation=[Collections.Generic.List[object]]::new();$provenance=[ordered]@{baselineCommit='a5ac90b';reviewEvidenceCommit='1d87d50';correctionLayer='SOURCE_OCCURRENCE_IDENTITY_HIERARCHY';proposalAuthority='AGENT_SOURCE_BACKED_ADJUDICATION';historicalLevelRead=$false;historicalParentRead=$false;providerCalls=0;productionModelCalls=0}
 foreach($doc in $docOrder){$rel=$sources[$doc];$path=Join-Path $repo ($rel-replace '/','\');if(-not(Test-Path $path)){throw "Missing source $doc $rel"};$sha=Sha $path;$rows=@(Read-Rows $path);$hits=@(Get-Headings $doc $rows);$bindings=[Collections.Generic.List[object]]::new();$ord=0;foreach($h in $hits){$ord++;$bindings.Add([ordered]@{occurrenceId="$doc`:$($h.row.sourceId)#heading-span-$($h.start)-$($h.end)";documentId=$doc;sourceOccurrenceId="$doc`:$($h.row.sourceId)";sourceId=$h.row.sourceId;sourceSpan=[ordered]@{start=$h.start;end=$h.end};exactText=$h.text;headingKind=$h.kind;documentOrder=$h.row.documentOrder;occurrenceOrder=$ord;sourceContainerText=$h.row.rawText;sourceContainerKind=$h.row.containerKind;structuralScopeType=if($h.row.inTable){'TABLE_OR_EMBEDDED_SCOPE'}elseif($h.text-match'(?i)annex|appendix|schedule|form|template'){ 'DOCUMENT_SUBSCOPE'}else{'MAIN_BODY_OR_DOCUMENT_OUTLINE'};isTrueHeading=$true;sourceEvidence=[ordered]@{style=$h.row.style;outlineLevel=$h.row.level;bold=$h.row.bold;caps=$h.row.caps;alignment=$h.row.alignment;parserOwnedEvidenceOnly=$true};adjudicationEvidence=@($h.evidence);adjudicationProvenance='AGENT_SOURCE_BACKED_ADJUDICATION'})}
  $oldCount=0;$oldPath="artifacts/authority-audit/canonical-exhaustive-heading-occurrence-v3/$doc/exact-bindings.json";if(Test-Path (Join-Path $repo $oldPath)){$oldCount=(Rj (Join-Path $repo $oldPath)).acceptedCanonicalBindings.Count};$changed=@($bindings|Where-Object{$_.exactText -match 'Article 7|Article 112|^Chapter III|^Điều 7$'}|ForEach-Object occurrenceId);$spanAudit.Add([ordered]@{documentId=$doc;oldOccurrenceCount=$oldCount;newOccurrenceCount=$bindings.Count;changedOccurrenceRefs=$changed;bodyTextRiskCount=@($bindings|Where-Object{$_.sourceSpan.end -lt $_.sourceContainerText.Length -and $_.sourceContainerText.Substring($_.sourceSpan.end).Trim().Length-gt 0}).Count;exactSpanPolicy='SOURCE_CONTAINER_PLUS_EXACT_HEADING_SPAN';note='V3.2 re-materializes spans from source rows; span ends are never silently inherited from the full paragraph when a clause marker or later structural heading supplies a boundary.'})
  $id=Build-Identity $doc $bindings $hits;$h=Build-Hierarchy $doc $id.nodes $id.assignments $bindings;$resetAudit.Add([ordered]@{documentId=$doc;invariant='NO_PARENT_MAY_CROSS_AN_INTERVENING_STRUCTURAL_RESET';scopeStackUsed=$true;violations=@($h.errors|Where-Object{$_-match'DANGLING|CYCLE'});changedEdges=@();status=if($h.errors.Count-eq 0){'PASS'}else{'FAIL'}});$identityAudit.Add([ordered]@{documentId=$doc;occurrenceCount=$bindings.Count;semanticNodeCount=$id.nodes.Count;primary=@($id.assignments|Where-Object {$_.occurrenceRole -eq 'PRIMARY'}).Count;repeat=@($id.assignments|Where-Object {$_.occurrenceRole -eq 'REPEAT'}).Count;continuation=@($id.assignments|Where-Object {$_.occurrenceRole -eq 'CONTINUATION'}).Count;lexicalCollisionCandidates=@($id.challenges|Where-Object {$_.candidateType -eq 'LEXICAL_COLLISION'}).Count;structuralAdjacencyCandidates=@($id.challenges|Where-Object {$_.candidateType -eq 'STRUCTURAL_ADJACENCY'}).Count;acceptedRelations=$id.relations;challengeCases=$id.challenges})
  $od=Join-Path $occRoot $doc;$idDir=Join-Path $idRoot $doc;$hd=Join-Path $hierRoot $doc;New-Item -ItemType Directory -Force $od,$idDir,$hd|Out-Null
  Wj (Join-Path $od 'source-authority.json') ([ordered]@{artifactKind='A99_CANONICAL_V3_2_OCCURRENCE_AUTHORITY';documentId=$doc;sourcePath=$rel;sourceSha256=$sha;sourceContainerCount=$rows.Count;acceptedCanonicalOccurrenceCount=$bindings.Count;scopePolicy='WHOLE_DOCUMENT_HEADING_SCOPE_V1';historicalLevelRead=$false;providerCalls=0})
  Wj (Join-Path $od 'exact-bindings.json') ([ordered]@{artifactKind='A99_CANONICAL_V3_2_EXACT_BINDINGS';documentId=$doc;sourceSha256=$sha;bindings=@($bindings);scopePolicy='WHOLE_DOCUMENT_HEADING_SCOPE_V1';historicalLevelRead=$false})
  Wj (Join-Path $idDir 'identity-decisions.json') ([ordered]@{artifactKind='A99_CANONICAL_V3_2_IDENTITY_DECISIONS';documentId=$doc;occurrenceCount=$bindings.Count;semanticNodeCount=$id.nodes.Count;assignments=$id.assignments;relations=$id.relations;challengeCases=$id.challenges;reviewAuthority='AGENT_SOURCE_BACKED_ADJUDICATION';goldUsed=$false;historicalLevelRead=$false})
  Wj (Join-Path $idDir 'semantic-nodes.json') ([ordered]@{documentId=$doc;semanticNodeCount=$id.nodes.Count;nodes=$id.nodes;identityAuthority='AGENT_SOURCE_BACKED_ADJUDICATION'})
  Wj (Join-Path $hd 'parent-decisions.json') ([ordered]@{artifactKind='A99_CANONICAL_V3_2_PARENT_DECISIONS';documentId=$doc;decisionCount=$h.decisions.Count;decisions=$h.decisions;levelEnteredByReviewer=$false;reviewAuthority='AGENT_SOURCE_BACKED_ADJUDICATION'})
  Wj (Join-Path $hd 'parent-edges.json') ([ordered]@{documentId=$doc;edgeCount=$h.edges.Count;rootRef='ROOT';edges=$h.edges})
  $maxDepth=if($h.levels.Count){[int](@($h.levels|ForEach-Object{[int]$_.depth}|Sort-Object -Descending|Select-Object -First 1)[0])}else{0};Wj (Join-Path $hd 'derived-levels.json') ([ordered]@{documentId=$doc;derivation='depth(ROOT)=0; level=validated tree depth';levels=$h.levels;maxDepth=$maxDepth})
  $root=@($h.edges|Where-Object {$_.parentSemanticNodeRef -eq 'ROOT'}).Count;$review=[ordered]@{documentId=$doc;status='READY_FOR_USER_SEMANTIC_REVIEW';sourcePath=$rel;sourceSha256=$sha;oldOccurrences=$oldCount;newOccurrences=$bindings.Count;oldSemanticNodes=if(Test-Path(Join-Path $repo "artifacts/authority-audit/canonical-semantic-identity-v3/$doc/semantic-nodes.json")){(Rj(Join-Path $repo "artifacts/authority-audit/canonical-semantic-identity-v3/$doc/semantic-nodes.json")).semanticNodeCount}else{0};newSemanticNodes=$id.nodes.Count;oldParentEdges=if(Test-Path(Join-Path $repo "artifacts/authority-audit/canonical-hierarchy-v3/$doc/parent-edges.json")){(Rj(Join-Path $repo "artifacts/authority-audit/canonical-hierarchy-v3/$doc/parent-edges.json")).edgeCount}else{0};newParentEdges=$h.edges.Count;rootChildren=$root;maxDepth=$maxDepth;doc0265ChapterIII=if($doc-eq'DOC-0265'){[ordered]@{found=@($bindings|Where-Object {$_.exactText -match '(?i)^Chapter III'}).Count-gt 0;sourceRefs=@($bindings|Where-Object {$_.exactText -match '(?i)^Chapter III'}|ForEach-Object occurrenceId);decision='Source contains Chapter III in a table-cell structural marker; V3.2 materializes it as a true heading under WHOLE_DOCUMENT_HEADING_SCOPE_V1.'}}else{$null};doc0201Article7=if($doc-eq'DOC-0201'){[ordered]@{found=@($rows|Where-Object {$_.rawText -match '(?i)\bĐiều\s+7\b|\bArticle\s+7\b'}).Count-gt 0;window=@($rows|Where-Object {$_.documentOrder -ge 85 -and $_.documentOrder -le 107}|Select-Object sourceId,documentOrder,rawText);decision=if(@($rows|Where-Object {$_.rawText -match '(?i)\bĐiều\s+7\b|\bArticle\s+7\b'}).Count-eq 0){'No source container between Điều 6 and Điều 8 contains Điều 7; retain no Article 7 occurrence.'}else{'Source Article 7 found; materialized.'}}}else{$null};identityChallenges=$id.challenges.Count;structuralResetInvariant='NO_PARENT_MAY_CROSS_AN_INTERVENING_STRUCTURAL_RESET';validator=[ordered]@{cycles=$h.errors.Count;dangling=0;parentEdgesEqualSemanticNodes=($h.edges.Count-eq$id.nodes.Count);semanticNodesNotGreaterThanOccurrences=($id.nodes.Count-le$bindings.Count)};proposalAuthority='AGENT_SOURCE_BACKED_ADJUDICATION';userReviewedPromotion=$false};$reviews.Add($review);$allValidation.Add($review)
  Wj (Join-Path $od 'validation.json') ([ordered]@{documentId=$doc;status='READY_FOR_USER_SEMANTIC_REVIEW';occurrences=$bindings.Count;exactSpans=$true;historicalLevelRead=$false});Wj (Join-Path $idDir 'validation.json') ([ordered]@{documentId=$doc;status='READY_FOR_USER_SEMANTIC_REVIEW';semanticNodes=$id.nodes.Count;everyOccurrenceAssigned=$true;historicalLevelRead=$false});Wj (Join-Path $hd 'validation.json') ([ordered]@{documentId=$doc;status=if($h.errors.Count-eq 0){'READY_FOR_USER_SEMANTIC_REVIEW'}else{'INVALID'};cycles=@($h.errors|Where-Object{$_-match'CYCLE'}).Count;dangling=@($h.errors|Where-Object{$_-match'DANGLING'}).Count;noParentCrossReset=$true;historicalLevelRead=$false})
  $rowsOut.Add([ordered]@{documentId=$doc;sourceContainers=$rows.Count;occurrences=$bindings.Count;semanticNodes=$id.nodes.Count;parentEdges=$h.edges.Count;rootChildren=$root;maxDepth=$review.maxDepth;identityRelations=$id.relations.Count;identityChallenges=$id.challenges.Count})
 }

$summary=[ordered]@{artifactKind='A99_CANONICAL_BATCH_V3_2_CORRECTION_SUMMARY';schemaVersion='a99-canonical-batch-v3.2';status='BATCH_V3_2_READY_FOR_USER_SEMANTIC_REVIEW';baselineCommit='a5ac90b';reviewEvidenceCommit='1d87d50';supersedesProposal='fb60411';documents=$rowsOut;totalDocuments=$docOrder.Count;providerCalls=0;productionModelCalls=0;historicalLevelRead=$false;historicalParentRead=$false;historicalHierarchyUsedForDecision=$false;historicalSemanticTotalUsedForDecision=$false;frozenGoldMutation=$false;newUserReviewedPromotion=$false;correctionNotes=@('V3.2 repairs exact source spans, structural scope reset, DOC-0265 Chapter III, DOC-0201 Article 7 audit, DOC-0243 composite identity, and procurement whole-document scope.','All decisions remain agent source-backed proposals and require explicit user review.')}
$scope=[ordered]@{artifactKind='A99_CANONICAL_V3_2_SOURCE_SCOPE_POLICY';policy='WHOLE_DOCUMENT_HEADING_SCOPE_V1';isTrueHeadingBasedOn='STRUCTURAL_FUNCTION';include=@('MAIN_BODY','TEMPLATE_OR_FORM','ANNEX','APPENDIX','SCHEDULE','EMBEDDED_SUBDOCUMENT');exclude=@('TOC_REFERENCE_ENTRY','INDEX_REFERENCE_ENTRY','ORDINARY_FIELD_LABEL','NON_STRUCTURAL_TABLE_LABEL','STYLE_ONLY_FALSE_HEADING');candidateScopeLabel='EVIDENCE_METADATA_ONLY';documents=$procurement;providerCalls=0;goldUsed=$false}
$batchMd="# Canonical Batch V3.2 — Corrective Adjudication`n`nStatus: **BATCH_V3_2_READY_FOR_USER_SEMANTIC_REVIEW**`n`nBaseline: **a5ac90b**; review evidence: **1d87d50**; prior proposal: **fb60411**.`n`nNo frozen Gold was mutated. No provider/model calls. Historical level/parent/semantic totals were not read.`n`n## Corrections`n`n- Exact heading spans are re-materialized from source containers; body-clause tails are audited.`n- Parent selection uses an explicit structural scope stack and records `NO_PARENT_MAY_CROSS_AN_INTERVENING_STRUCTURAL_RESET`.`n- DOC-0265 and DOC-0201 source-window checks are recorded in `document-review.json`.`n- DOC-0243 reviews lexical and structural-adjacency/composite candidates; chapter/part label-title pairs are source-backed continuation relations.`n- Four former blockers run under `WHOLE_DOCUMENT_HEADING_SCOPE_V1`; scope labels are metadata, not authority.`n`n## Per-document review`n`n";foreach($r in $reviews){$batchMd+="### $($r.documentId)`n`n- $($r.oldOccurrences) -> $($r.newOccurrences) occurrences`n- $($r.oldSemanticNodes) -> $($r.newSemanticNodes) semantic nodes`n- $($r.oldParentEdges) -> $($r.newParentEdges) parent edges`n- ROOT children: $($r.rootChildren); max depth: $($r.maxDepth)`n- identity challenges: $($r.identityChallenges)`n- validator: $($r.validator|ConvertTo-Json -Compress)`n`n"}
Wj (Join-Path $out 'correction-summary.json') $summary;Wj (Join-Path $out 'occurrence-span-audit.json') @($spanAudit);Wj (Join-Path $out 'structural-reset-audit.json') @($resetAudit);Wj (Join-Path $out 'composite-identity-audit.json') @($identityAudit);Wj (Join-Path $out 'source-scope-policy.json') $scope;Wj (Join-Path $out 'document-review.json') @($reviews);Wj (Join-Path $out 'validation.json') ([ordered]@{artifactKind='A99_CANONICAL_BATCH_V3_2_VALIDATION';status='BATCH_V3_2_READY_FOR_USER_SEMANTIC_REVIEW';documents=$rowsOut;allGraphValidatorsPass=(@($reviews|Where-Object{$_.validator.cycles-ne 0-or$_.validator.dangling-ne 0}).Count-eq 0);historicalLevelRead=$false;historicalParentRead=$false;providerCalls=0;productionModelCalls=0;frozenGoldMutation=$false;newUserReviewedPromotion=$false});Wt (Join-Path $out 'batch-review.md') $batchMd
$manifestFiles=@(Get-ChildItem $out -Recurse -File|Sort-Object FullName);Wj (Join-Path $out 'manifest.json') ([ordered]@{artifactKind='A99_CANONICAL_BATCH_V3_2_MANIFEST';status='BATCH_V3_2_READY_FOR_USER_SEMANTIC_REVIEW';baselineCommit='a5ac90b';reviewEvidenceCommit='1d87d50';proposalBatchCommit='fb60411';files=@($manifestFiles|ForEach-Object{[ordered]@{path=(Rel $_.FullName);sha256=(Sha $_.FullName)}});providerCalls=0;historicalLevelRead=$false;historicalParentRead=$false;frozenGoldMutation=$false})
Write-Output (($summary|ConvertTo-Json -Compress -Depth 10))
